// GBL 가이드 2차 세트(4개국어) — 실전 운영(실드·교체·버프), 시스템(랭크·레이팅), 육성 투자(그림자·XL), 레이드 입문.
// guides.ts의 GUIDES에 병합되어 목록·상세·사이트맵에 자동 반영. 수치 근거:
// 실드 2장/배틀 · 교체 후 60초 타이머 · 능력치 단계 ±4(분모 4) · 그림자 공격 1.2/방어 0.833 ·
// XL 사탕 레벨 40→50 총 296개 · 베스트버디 +1레벨 · 레이드 포획 레벨 20(날씨 부스트 25) · 레이드 IV 하한 10.
import type { Guide } from "./guides";

export const GUIDES_EXTRA: Record<string, Guide> = {
  "shields-baiting": {
    updated: "2026-09-12",
    keywords: {
      ko: ["포켓몬고 실드 사용법", "GBL 베이팅", "배틀리그 실드 타이밍", "포켓몬고 실드 언제", "PvP 베이트", "실드 빼기"],
      en: ["Pokémon GO shield strategy", "GBL baiting", "when to shield Pokémon GO", "PvP bait", "shield management GBL"],
      ja: ["ポケモンGO シールド 使い方", "GBL ベイト", "バトルリーグ シールド タイミング", "PvP ベイト", "シールド剥がし"],
      "zh-TW": ["寶可夢GO 護盾 用法", "GBL 騙盾", "對戰聯盟 護盾 時機", "PvP 騙盾", "護盾管理"],
    },
    ko: {
      title: "GBL 실드 사용법과 베이팅 — 실드 2장을 어디에 쓸 것인가",
      desc: "포켓몬 GO 배틀리그에서 승패를 가장 크게 가르는 것은 실드 2장의 사용처입니다. 실드가 막는 것과 막지 못하는 것, 베이팅의 원리, 실드 우위·에너지 우위 개념, 리그별 실드 판단 기준을 정리했습니다.",
      sections: [
        { p: "GBL에서 실드는 배틀 전체를 통틀어 트레이너당 2장뿐입니다. 포켓몬마다 2장이 아니라 파티 3마리가 실드 2장을 나눠 씁니다. 그래서 실드는 '위험할 때 누르는 버튼'이 아니라 '배틀 전체의 자원'입니다. 실드를 잘 쓴다는 것은 곧 어디에 안 쓰는지를 안다는 뜻입니다." },
        { h: "실드가 막는 것과 못 막는 것", p: "실드는 상대 차지 기술의 데미지를 1로 줄입니다. 그러나 기술에 붙은 능력치 변화(내 방어 하락, 상대 공격 상승 등)는 실드로 막아도 그대로 적용됩니다. 예를 들어 상대가 방어 하락 부가효과가 있는 기술을 쓰면 실드를 써도 내 방어는 떨어집니다. 실드 사용 화면이 뜨는 동안에도 상대 빠른 기술은 계속 들어오므로, 실드는 '차지 기술 데미지'만 막는 도구라고 기억하세요." },
        { h: "실드를 쓰지 말아야 할 순간", p: "첫째, 그 차지 기술을 맞아도 내 포켓몬이 자기 역할(다음 차지 한 번 더 던지기, 상대 실드 빼기)을 완수할 수 있을 때. 둘째, 지금 상대 포켓몬은 내 다음 포켓몬이 어차피 이기는 상대일 때. 셋째, 이미 불리한 매치업이라 실드를 써도 결과가 안 바뀔 때. 이때 실드를 아끼면 나중에 정말 뒤집을 수 있는 매치업에서 2장을 쓸 수 있습니다." },
        { h: "실드를 써야 하는 순간", p: "첫째, 이 포켓몬을 살려야 다음 매치업이 이기는 구조일 때(예: 상대의 마지막 포켓몬을 내 이 포켓몬만 잡을 수 있음). 둘째, 실드를 쓰면 내가 차지 기술을 먼저 던져 상대 실드를 빼거나 상대를 잡을 수 있을 때. 셋째, 효과굉장 고위력 기술이 들어와 한 방에 HP 절반 이상이 날아갈 때. 판단 기준은 '이 실드로 내가 얻는 것이 상대 실드 1장 이상의 가치인가'입니다." },
        { h: "베이팅의 원리", p: "베이팅은 저에너지(35~45) 기술을 먼저 던져 상대 실드를 빼고, 상대 실드가 없어졌을 때 고에너지 기술로 큰 데미지를 넣는 전술입니다. 상대는 어떤 기술이 날아오는지 발동 전에 알 수 없으므로(기술 이름은 발동 후 표시), 위협적인 기술을 가진 포켓몬이면 저에너지 기술에도 실드를 쓰게 됩니다. 반대로 상대가 내 저에너지 기술을 안 막고 버티면 베이팅은 실패하고 데미지 손해를 봅니다. 그래서 베이팅은 '상대가 실드를 쓸 이유가 있는 포켓몬'만 할 수 있습니다." },
        { h: "베이트 여부를 결정하는 기준", p: "① 상대 남은 HP: 고에너지 기술로 지금 잡을 수 있으면 베이트 없이 바로 던집니다. ② 내 남은 HP: 한 번 더 차지를 던질 시간이 없으면 지금 가장 센 기술을 씁니다. ③ 상대 실드 개수: 상대 실드가 0장이면 베이트는 무의미합니다. ④ 에너지 차이: 상대가 곧 차지 기술을 던질 상황이면 베이트 기술을 던지는 사이 상대가 먼저 큰 기술을 넣을 수 있습니다. 시뮬레이터의 0·1·2 실드 시나리오는 이 판단이 승패를 어떻게 바꾸는지 보여줍니다." },
        { h: "실드 우위와 에너지 우위", p: "GBL 중반전은 '상대보다 실드가 1장 더 있는가'(실드 우위)와 '상대보다 에너지가 더 차 있는가'(에너지 우위)로 설명됩니다. 실드 우위가 있으면 상대의 베이트를 무시하고 진짜 큰 기술만 막을 수 있고, 에너지 우위가 있으면 상대가 교체해 들어오는 포켓몬에 바로 차지 기술을 넣을 수 있습니다. 실드 2장을 초반에 다 쓰면 후반 두 마리는 상대의 모든 차지 기술을 그대로 맞아야 합니다. 첫 매치업에서 실드 2장을 모두 쓰는 것은 대개 패배 수순입니다." },
        { h: "리그별 실드 판단 차이", p: "슈퍼리그는 HP가 낮고 저에너지 기술이 많아 베이팅이 활발하고 실드 한 장의 가치가 큽니다. 하이퍼리그는 중간, 마스터리그는 전설 포켓몬의 고위력 기술이 한 방에 HP 절반을 날리므로 실드를 '필수 방어'로 쓰게 되고, 동시 차징 우선권(CMP)이 실드 타이밍을 좌우합니다. 같은 실드 2장이라도 리그마다 쓰는 법이 다르니, 리그별 티어표와 실측 메타를 보고 '지금 리그에서 실드를 뺏는 기술이 무엇인지'를 익혀 두세요." },
        { h: "연습 방법", p: "배틀 후 로그(내 전적)에서 실드를 어디에 썼는지 복기하고, 시뮬레이터에서 같은 매치업을 0·1·2 실드로 돌려 보세요. '이 실드를 아꼈으면 다음 매치업이 이겼는가'를 확인하는 습관이 랭크 상승의 가장 빠른 길입니다." },
      ],
    },
    en: {
      title: "GBL Shield Strategy and Baiting — Where Your Two Shields Should Go",
      desc: "Nothing decides a Pokémon GO Battle League match more than where you spend your two shields. What shields block and don't block, how baiting works, shield and energy advantage, and league-by-league shield rules.",
      sections: [
        { p: "In GBL you get two shields for the whole battle, not two per Pokémon. Your three Pokémon share them. That makes shields a resource for the entire match rather than a panic button. Using shields well mostly means knowing where not to use them." },
        { h: "What a shield blocks and what it doesn't", p: "A shield reduces a Charged Attack's damage to 1. It does not stop the stat changes attached to that move: if the opponent's move lowers your Defense or raises their Attack, that still happens through the shield. Fast Attacks keep landing while the shield prompt is up. Think of a shield as blocking Charged Attack damage only." },
        { h: "When not to shield", p: "First, when your Pokémon can still do its job (throw one more Charged Attack, pull a shield) after taking the hit. Second, when the opposing Pokémon loses to your next Pokémon anyway. Third, when the matchup is already lost and a shield won't change the result. Saving shields here lets you spend both later in a matchup you can actually flip." },
        { h: "When to shield", p: "First, when keeping this Pokémon alive wins the next matchup (for example, it is the only one that beats the opponent's last Pokémon). Second, when shielding lets you throw first and pull a shield or close out the Pokémon. Third, when a super-effective, high-power move would remove more than half your HP. The test is simple: is what this shield buys me worth at least one of their shields?" },
        { h: "How baiting works", p: "Baiting means throwing a low-energy move (35–45 energy) to draw a shield, then landing your high-energy move once the shields are gone. The opponent cannot see which move is coming until it fires, so against a Pokémon with a threatening nuke they tend to shield even the cheap move. If they call your bluff and take the cheap move, the bait fails and you lose damage. Baiting only works from a Pokémon the opponent has a reason to shield." },
        { h: "Deciding whether to bait", p: "① Opponent's HP: if the big move kills right now, skip the bait. ② Your HP: if you won't survive to throw again, throw the strongest move now. ③ Their shields: with zero shields left, baiting is pointless. ④ Energy gap: if they are about to throw, the turns spent on a bait can let them land first. The simulator's 0/1/2-shield scenarios show exactly how these choices change the result." },
        { h: "Shield advantage and energy advantage", p: "The midgame of GBL is best described by two questions: do I have one more shield than my opponent (shield advantage), and do I have more energy than they do (energy advantage)? Shield advantage lets you ignore baits and block only the real threats; energy advantage lets you punish whatever they switch in. Burning both shields in the first matchup usually loses the game, because your last two Pokémon must eat every Charged Attack." },
        { h: "How shields differ by league", p: "Great League has low HP pools and many cheap moves, so baiting is constant and each shield is precious. Ultra League sits in between. Master League Legendaries can delete half an HP bar in one move, so shields become mandatory defense and Charged Move Priority (CMP) decides who throws first. Study the league's tier list and live meta to learn which moves pull shields in the current format." },
        { h: "How to practice", p: "After each battle, review your log to see where the shields went, then replay the same matchup in the simulator with 0, 1 and 2 shields. Asking 'would the next matchup have won if I saved this shield?' is the fastest route to climbing." },
      ],
    },
    ja: {
      title: "GBLシールドの使い方とベイト — 2枚のシールドをどこに使うか",
      desc: "ポケモンGOバトルリーグで勝敗を最も左右するのはシールド2枚の使いどころです。シールドが防げるもの・防げないもの、ベイトの原理、シールド有利・エネルギー有利の考え方、リーグ別のシールド判断をまとめました。",
      sections: [
        { p: "GBLのシールドはバトル全体でトレーナーごとに2枚だけです。ポケモンごとに2枚ではなく、パーティ3匹で2枚を分け合います。つまりシールドは「危ないときに押すボタン」ではなく「バトル全体の資源」です。シールドがうまいとは、どこで使わないかを知っていることです。" },
        { h: "シールドが防ぐもの・防げないもの", p: "シールドは相手のゲージわざのダメージを1にします。しかしわざに付いた能力変化（自分の防御ダウン、相手の攻撃アップなど）はシールドしても適用されます。例えば防御ダウンの追加効果があるわざをシールドしても自分の防御は下がります。シールド画面が出ている間も相手の通常わざは入り続けるため、シールドは「ゲージわざのダメージ」だけを防ぐ道具と覚えてください。" },
        { h: "シールドを使ってはいけない場面", p: "第一に、そのゲージわざを受けても自分のポケモンが役割（もう1回ゲージわざを撃つ、相手のシールドを剥がす）を果たせるとき。第二に、今の相手ポケモンは次の自分のポケモンがどうせ勝てる相手のとき。第三に、すでに不利対面でシールドしても結果が変わらないとき。ここで温存すれば、後で本当に覆せる対面で2枚使えます。" },
        { h: "シールドを使うべき場面", p: "第一に、このポケモンを残せば次の対面が勝てる構造のとき（例：相手のラストを自分のこのポケモンしか倒せない）。第二に、シールドすれば自分が先にゲージわざを撃って相手のシールドを剥がす、または倒せるとき。第三に、効果抜群の高威力わざで一撃でHPの半分以上が飛ぶとき。判断基準は「このシールドで得るものが相手のシールド1枚以上の価値か」です。" },
        { h: "ベイトの原理", p: "ベイトとは低エネルギー（35〜45）のわざを先に撃って相手のシールドを剥がし、シールドがなくなったところに高エネルギーわざで大ダメージを入れる戦術です。相手はどのわざが来るか発動前には分からない（わざ名は発動後に表示）ため、脅威となるわざを持つポケモンなら低エネルギーわざにもシールドを切ります。逆に相手が低エネルギーわざを受け流せばベイトは失敗し、ダメージで損をします。だからベイトは「相手がシールドを切る理由のあるポケモン」でしかできません。" },
        { h: "ベイトするかの判断基準", p: "①相手の残りHP：高エネルギーわざで今倒せるならベイトせず撃つ。②自分の残りHP：もう1回撃つ時間がなければ今一番強いわざを撃つ。③相手のシールド枚数：0枚ならベイトは無意味。④エネルギー差：相手がまもなくゲージわざを撃つ状況なら、ベイトの間に相手が先に大技を入れてくる。シミュレーターの0・1・2シールドシナリオはこの判断が勝敗をどう変えるかを示します。" },
        { h: "シールド有利とエネルギー有利", p: "GBLの中盤は「相手よりシールドが1枚多いか」（シールド有利）と「相手よりエネルギーが貯まっているか」（エネルギー有利）で説明できます。シールド有利なら相手のベイトを無視して本命だけ防げ、エネルギー有利なら交代で出てきたポケモンにすぐゲージわざを入れられます。序盤でシールド2枚を使い切ると後半の2匹は相手の全ゲージわざをそのまま受けることになります。最初の対面でシールド2枚を使い切るのはたいてい負け筋です。" },
        { h: "リーグ別のシールド判断の違い", p: "スーパーリーグはHPが低く低エネルギーわざが多いためベイトが活発でシールド1枚の価値が大きいです。ハイパーリーグは中間、マスターリーグは伝説の高威力わざが一撃でHP半分を削るためシールドが「必須防御」になり、同時ゲージの優先権（CMP）がシールドのタイミングを左右します。同じ2枚でもリーグごとに使い方が違うので、リーグ別ティア表と実測メタで「今のリーグでシールドを剥がすわざは何か」を覚えておきましょう。" },
        { h: "練習方法", p: "バトル後にログ（自分の戦績）でシールドをどこに使ったか振り返り、シミュレーターで同じ対面を0・1・2シールドで回してみましょう。「このシールドを温存していたら次の対面は勝てたか」を確認する習慣がランク上昇の最短ルートです。" },
      ],
    },
    "zh-TW": {
      title: "GBL 護盾用法與騙盾 — 兩面護盾該用在哪裡",
      desc: "寶可夢 GO 對戰聯盟中，最影響勝負的就是兩面護盾的用途。整理護盾能擋與不能擋的東西、騙盾原理、護盾優勢・能量優勢概念，以及各聯盟的護盾判斷基準。",
      sections: [
        { p: "GBL 的護盾整場對戰每位訓練家只有 2 面，不是每隻寶可夢 2 面，而是隊伍 3 隻共用 2 面。因此護盾不是「危險時按的按鈕」，而是「整場對戰的資源」。所謂會用護盾，就是知道哪裡不該用。" },
        { h: "護盾能擋與不能擋的東西", p: "護盾將對手特殊招式的傷害降為 1。但招式附帶的能力變化（我方防禦下降、對手攻擊上升等）即使開盾仍會生效。例如對手使用附帶防禦下降效果的招式，開盾後我方防禦仍會下降。護盾畫面出現期間對手的一般招式仍持續命中，請記住護盾只擋「特殊招式傷害」。" },
        { h: "不該開盾的時機", p: "第一，即使吃下該特殊招式，我方寶可夢仍能完成任務（再丟一次特殊招式、拔掉對手護盾）時。第二，當前對手反正會輸給我方下一隻時。第三，已是不利對面，開盾也改變不了結果時。此時省下護盾，之後才能在真正能翻盤的對面用上 2 面。" },
        { h: "該開盾的時機", p: "第一，保住這隻就能贏下一個對面時（例：只有這隻能打贏對手最後一隻）。第二，開盾後我方能先丟特殊招式拔盾或擊倒對手時。第三，效果絕佳的高威力招式一擊會削掉一半以上 HP 時。判斷基準是「這面護盾換來的價值是否至少等於對手一面護盾」。" },
        { h: "騙盾的原理", p: "騙盾是先丟低能量（35〜45）招式引誘對手開盾，待對手沒盾後再以高能量招式造成大傷害的戰術。對手在發動前無法得知是哪個招式（招式名稱發動後才顯示），因此面對擁有威脅性招式的寶可夢，連低能量招式也會開盾。反之若對手硬吃低能量招式，騙盾就失敗並損失傷害。所以只有「對手有理由開盾的寶可夢」才能騙盾。" },
        { h: "是否騙盾的判斷基準", p: "① 對手剩餘 HP：高能量招式現在就能擊倒，就不騙直接丟。② 我方剩餘 HP：沒時間再丟一次，就用現在最強的招式。③ 對手護盾數：0 面時騙盾沒有意義。④ 能量差：對手即將丟特殊招式時，騙盾期間對手可能先打出大招。模擬器的 0/1/2 護盾情境會顯示這些判斷如何改變勝負。" },
        { h: "護盾優勢與能量優勢", p: "GBL 的中盤可以用「我比對手多一面護盾嗎」（護盾優勢）和「我的能量比對手多嗎」（能量優勢）來解釋。有護盾優勢就能無視對手的騙盾、只擋真正的大招；有能量優勢就能對換場進來的寶可夢立即丟特殊招式。開局就用光 2 面護盾，後面兩隻就得硬吃對手所有特殊招式。第一個對面就用完 2 面護盾，通常就是敗局。" },
        { h: "各聯盟的護盾判斷差異", p: "超級聯盟 HP 低、低能量招式多，騙盾頻繁且每面護盾價值高。高級聯盟居中，大師聯盟傳說寶可夢的高威力招式一擊削半，護盾成為「必要防禦」，同時特殊招式優先權（CMP）左右開盾時機。同樣 2 面護盾，各聯盟用法不同，請透過各聯盟強度表與實測環境熟悉「當前聯盟中會拔盾的招式是什麼」。" },
        { h: "練習方法", p: "對戰後在紀錄（我的戰績）中回顧護盾用在哪裡，再到模擬器以 0・1・2 護盾重跑同一對面。養成確認「若省下這面護盾，下一個對面會贏嗎」的習慣，是提升段位最快的方法。" },
      ],
    },
  },

  "switching-and-alignment": {
    updated: "2026-09-12",
    keywords: {
      ko: ["포켓몬고 교체 타이밍", "GBL 스위치", "배틀리그 교체", "세이프 스왑", "GBL 정렬", "교체 타이머 60초"],
      en: ["Pokémon GO switch timing", "GBL safe swap", "switch timer 60 seconds", "GBL alignment", "when to switch GBL"],
      ja: ["ポケモンGO 交代 タイミング", "GBL セーフスワップ", "交代タイマー 60秒", "GBL アライメント", "バトルリーグ 交代"],
      "zh-TW": ["寶可夢GO 換場 時機", "GBL 安全換場", "換場計時 60秒", "GBL 對位", "對戰聯盟 換場"],
    },
    ko: {
      title: "GBL 교체 타이밍과 정렬 — 60초 교체 타이머를 이기는 법",
      desc: "포켓몬 GO 배틀리그의 교체(스위치)는 실드 다음으로 중요한 자원입니다. 60초 교체 타이머의 의미, 세이프 스왑, 선봉·클로저의 역할, 에너지·정렬 우위, 교체를 강요당하는 상황과 대응법을 정리했습니다.",
      sections: [
        { p: "GBL은 3대3이지만 한 번에 싸우는 것은 1대1입니다. 그래서 '누가 누구와 싸우게 만드는가'가 승패의 절반입니다. 교체는 그 대진을 내가 고르는 유일한 수단이고, 교체 후에는 60초 동안 다시 교체할 수 없습니다. 이 60초를 어떻게 쓰느냐가 교체 실력입니다." },
        { h: "교체 타이머의 기본 규칙", p: "교체를 하면 60초 타이머가 시작되고, 그 동안은 다시 교체할 수 없습니다. 단, 내 포켓몬이 쓰러지면 타이머와 무관하게 다음 포켓몬을 낼 수 있습니다. 상대도 같은 규칙이므로, 상대가 방금 교체했다면 상대는 60초 동안 지금 포켓몬으로 버텨야 합니다. 이때 내가 유리한 포켓몬으로 교체하면 상대는 도망칠 수 없습니다. 이것이 교체의 가장 기본적인 이득입니다." },
        { h: "선봉(리드)의 역할", p: "선봉은 상대 선봉과 반드시 싸워야 하고, 여기서 첫 실드·에너지·교체 판단이 갈립니다. 좋은 선봉은 ① 불리해도 크게 지지 않고(안전) ② 상대 실드를 잘 빼며(저에너지 기술) ③ 교체가 들어와도 버틸 내구를 갖춘 포켓몬입니다. 선봉이 상대 선봉에 크게 불리하면 즉시 교체해 '세이프 스왑'을 내고, 유리하면 상대의 교체를 받아낼 준비를 합니다." },
        { h: "세이프 스왑과 클로저", p: "세이프 스왑은 선봉이 불리할 때 교체해 들어오는 두 번째 포켓몬으로, 어떤 상대가 나와도 크게 지지 않는 범용성이 핵심입니다. 클로저는 마지막에 남아 실드 없이도 상대를 마무리하는 포켓몬으로, 높은 내구와 고위력 기술이 필요합니다. 파티는 보통 '선봉 – 세이프 스왑 – 클로저' 세 역할로 구성하며, 세 마리가 서로의 카운터를 커버하도록 짜야 합니다." },
        { h: "교체로 얻는 에너지·정렬 우위", p: "내가 교체해 들어간 포켓몬이 상대를 잡으면, 상대는 다음 포켓몬을 내야 하고 내 포켓몬은 에너지를 안고 그 상대를 맞이합니다. 이렇게 '내 포켓몬이 에너지를 가진 채 상대의 새 포켓몬을 맞는' 상태를 에너지 우위라 하고, 상대가 교체를 강요당해 매치업이 내게 유리하게 정리된 상태를 정렬(alignment) 우위라 합니다. 실드 2장을 아끼는 이유도 결국 이 정렬을 만들기 위해서입니다." },
        { h: "교체를 강요당하는 상황", p: "상대가 내 선봉에 유리한 포켓몬으로 교체해 들어오면 나는 ① 그대로 싸우고 실드를 쓴다 ② 내 세이프 스왑으로 교체한다 중 하나를 골라야 합니다. 이때 상대의 60초 타이머가 돌고 있으므로, 내가 지금 교체하면 상대는 내 새 포켓몬을 60초 동안 피할 수 없습니다. 반대로 내가 먼저 교체했고 타이머가 돌고 있을 때 상대가 카운터로 교체하면 나는 60초 동안 '갇힌' 상태가 되므로, 타이머가 도는 동안은 실드로 버틸 수밖에 없습니다." },
        { h: "타이머가 끝나기 전에 할 일", p: "교체 후 60초는 생각보다 깁니다. 그 동안 ① 상대 실드를 최대한 빼고 ② 내 포켓몬의 에너지를 최대한 채운 뒤 ③ 타이머가 끝나는 순간 유리한 포켓몬으로 다시 교체하는 것이 이상적입니다. 특히 상대가 차지 기술을 던지기 직전 교체하면, 그 기술은 새로 나온 내 포켓몬에게 들어가므로 반감 타입으로 받아내는 '교체 흡수'가 가능합니다." },
        { h: "실전 체크리스트", p: "① 상대가 교체했나? 그렇다면 상대는 60초 동안 못 도망간다. ② 내 타이머가 돌고 있나? 그렇다면 교체는 없다, 실드와 에너지로 버틴다. ③ 내 다음 포켓몬은 지금 상대와 그 뒤의 상대를 다 커버하나? ④ 상대의 마지막 포켓몬이 무엇일지 예상되나(리그 실측 메타에서 자주 나오는 조합)? 이 네 가지를 매 교체 전에 자문하면 실수가 크게 줄어듭니다." },
        { h: "연습 팁", p: "티어표에서 선봉·세이프 스왑·클로저 적성이 높은 포켓몬을 확인하고, 시뮬레이터의 팀 빌더로 내 3마리가 메타 상위 상대를 얼마나 커버하는지 점검하세요. 배틀 로그를 보며 '교체를 안 했으면 어땠을까'를 복기하는 것도 좋은 훈련입니다." },
      ],
    },
    en: {
      title: "GBL Switch Timing and Alignment — Beating the 60-Second Switch Timer",
      desc: "Switching is the second most important resource in the Go Battle League after shields. What the 60-second switch timer means, safe swaps, lead and closer roles, energy and alignment advantage, and how to respond when you are forced to switch.",
      sections: [
        { p: "GBL is 3v3, but only one Pokémon fights at a time, so deciding who fights whom is half the game. Switching is your only way to choose that matchup, and after a switch you cannot switch again for 60 seconds. How you use those 60 seconds is what switching skill means." },
        { h: "Switch timer basics", p: "Switching starts a 60-second timer during which you cannot switch again. If your Pokémon faints, you bring in the next one regardless of the timer. The same rules apply to your opponent: if they just switched, they are locked into their current Pokémon for 60 seconds. If you then switch to a favorable counter, they cannot escape. That is the most basic profit from a switch." },
        { h: "The lead's job", p: "Your lead always fights their lead, and the first shield, energy and switch decisions happen here. A good lead ① does not lose badly even in a bad matchup, ② pulls shields well with cheap moves, and ③ has enough bulk to absorb a counter-switch. If the lead is heavily disadvantaged, switch out immediately to your safe swap; if it is favorable, prepare to receive their switch." },
        { h: "Safe swap and closer", p: "The safe swap is the second Pokémon you bring in when the lead is losing; its key trait is not losing badly to anything. The closer is the last Pokémon standing, expected to finish the game without shields, so it needs high bulk and powerful moves. Most teams are built around lead – safe swap – closer, with the three covering each other's counters." },
        { h: "Energy and alignment advantage from switching", p: "If the Pokémon you switch in knocks out its opponent, they must bring in their next Pokémon while yours meets it with stored energy. Meeting a fresh opponent with energy already banked is energy advantage; forcing the opponent into matchups that favor you is alignment advantage. Saving shields is ultimately about creating this alignment." },
        { h: "When you are forced to switch", p: "If the opponent switches in a counter to your lead, you must either ① stay and spend shields, or ② switch to your safe swap. Their 60-second timer is running, so if you switch now they cannot dodge your new Pokémon for a full minute. The reverse is also true: if you switched first and they counter-switch, you are trapped for 60 seconds and must hold with shields." },
        { h: "What to do before the timer ends", p: "Sixty seconds is longer than it feels. Use it to ① pull as many shields as possible, ② bank as much energy as you can, and ③ switch again to a favorable Pokémon the moment the timer ends. Switching just before an opponent's Charged Attack lands sends that move into your incoming Pokémon, letting you absorb it on a resisted type." },
        { h: "In-battle checklist", p: "① Did the opponent just switch? Then they cannot run for 60 seconds. ② Is my timer running? Then no switch is possible; hold with shields and energy. ③ Does my next Pokémon cover both the current opponent and the one behind it? ④ Can I predict their last Pokémon from the league's common cores (see the live meta)? Asking these four before every switch removes most mistakes." },
        { h: "How to practice", p: "Check the tier list for Pokémon with high lead, switch and closer scores, then use the simulator's team builder to see how well your three cover the top meta threats. Reviewing battle logs and asking 'what if I hadn't switched?' is excellent training." },
      ],
    },
    ja: {
      title: "GBLの交代タイミングとアライメント — 60秒の交代タイマーを制する",
      desc: "ポケモンGOバトルリーグの交代（スイッチ）はシールドに次いで重要な資源です。60秒交代タイマーの意味、セーフスワップ、先発・クローザーの役割、エネルギー・アライメント有利、交代を強いられる状況と対応をまとめました。",
      sections: [
        { p: "GBLは3対3ですが、同時に戦うのは1対1です。だから「誰と誰を戦わせるか」が勝敗の半分を決めます。交代はその対面を自分で選べる唯一の手段で、交代後は60秒間再交代できません。この60秒をどう使うかが交代の実力です。" },
        { h: "交代タイマーの基本ルール", p: "交代すると60秒のタイマーが始まり、その間は再交代できません。ただし自分のポケモンが倒れればタイマーに関係なく次のポケモンを出せます。相手も同じルールなので、相手が今交代したなら相手は60秒間そのポケモンで耐えなければなりません。そこで自分が有利なポケモンに交代すれば、相手は逃げられません。これが交代の最も基本的な利益です。" },
        { h: "先発（リード）の役割", p: "先発は相手の先発と必ず戦い、ここで最初のシールド・エネルギー・交代の判断が分かれます。良い先発は①不利でも大きく負けず（安全）②相手のシールドを剥がしやすく（低エネルギーわざ）③交代を受けても耐える耐久を持つポケモンです。先発が相手の先発に大きく不利なら即交代して「セーフスワップ」を出し、有利なら相手の交代を受ける準備をします。" },
        { h: "セーフスワップとクローザー", p: "セーフスワップは先発が不利なときに交代で出す2匹目で、どんな相手が出ても大きく負けない汎用性が核心です。クローザーは最後に残ってシールドなしでも相手を仕留めるポケモンで、高い耐久と高威力わざが必要です。パーティは通常「先発 – セーフスワップ – クローザー」の3役で構成し、3匹が互いのカウンターをカバーするように組みます。" },
        { h: "交代で得るエネルギー・アライメント有利", p: "交代で出したポケモンが相手を倒せば、相手は次のポケモンを出さねばならず、自分のポケモンはエネルギーを抱えたままその相手を迎えます。このように「エネルギーを持った状態で相手の新しいポケモンを迎える」状態をエネルギー有利、相手が交代を強いられて対面が自分に有利に整理された状態をアライメント有利と呼びます。シールド2枚を温存する理由も結局この整列を作るためです。" },
        { h: "交代を強いられる状況", p: "相手が自分の先発に有利なポケモンで交代してきたら、自分は①そのまま戦ってシールドを使う②自分のセーフスワップに交代する、のどちらかを選びます。このとき相手の60秒タイマーが動いているので、今交代すれば相手は自分の新しいポケモンを60秒間避けられません。逆に自分が先に交代してタイマーが動いているときに相手がカウンターで交代すると、自分は60秒間「閉じ込められた」状態になるため、タイマーが動く間はシールドで耐えるしかありません。" },
        { h: "タイマーが終わる前にすること", p: "交代後の60秒は思ったより長いです。その間に①相手のシールドをできるだけ剥がし②自分のポケモンのエネルギーをできるだけ貯め③タイマーが終わる瞬間に有利なポケモンへ再交代するのが理想です。特に相手がゲージわざを撃つ直前に交代すると、そのわざは新しく出た自分のポケモンに入るため、半減タイプで受け止める「交代吸収」ができます。" },
        { h: "実戦チェックリスト", p: "①相手は交代したか？ならば相手は60秒間逃げられない。②自分のタイマーは動いているか？ならば交代はない、シールドとエネルギーで耐える。③自分の次のポケモンは今の相手とその後ろの相手を両方カバーできるか？④相手のラストが何か予想できるか（リーグ実測メタでよく出る組み合わせ）？この4つを交代前に自問すればミスが大きく減ります。" },
        { h: "練習のコツ", p: "ティア表で先発・セーフスワップ・クローザー適性が高いポケモンを確認し、シミュレーターのチームビルダーで自分の3匹がメタ上位をどれだけカバーできるか点検しましょう。バトルログを見て「交代しなかったらどうだったか」を振り返るのも良い訓練です。" },
      ],
    },
    "zh-TW": {
      title: "GBL 換場時機與對位 — 戰勝 60 秒換場計時",
      desc: "寶可夢 GO 對戰聯盟的換場是僅次於護盾的重要資源。整理 60 秒換場計時的意義、安全換場、先發・收尾手的角色、能量・對位優勢，以及被迫換場的情況與應對。",
      sections: [
        { p: "GBL 雖是 3 對 3，但同時只有 1 對 1 在戰鬥。因此「讓誰對上誰」決定了一半勝負。換場是唯一能自己選擇對面的手段，換場後 60 秒內無法再換。如何運用這 60 秒，就是換場的功力。" },
        { h: "換場計時的基本規則", p: "換場後開始 60 秒計時，期間無法再換場。但若我方寶可夢倒下，無論計時都可派出下一隻。對手也適用相同規則，所以對手剛換場時，必須用當前寶可夢撐 60 秒。此時我方換上有利的寶可夢，對手就無法逃脫。這是換場最基本的收益。" },
        { h: "先發的角色", p: "先發必定與對手先發交戰，第一面護盾、能量與換場判斷都在此分歧。好的先發 ① 即使不利也不會大輸（安全）② 善於拔盾（低能量招式）③ 有足夠耐久承受對手換場。先發若明顯不利就立即換出「安全換場」，有利則準備接下對手的換場。" },
        { h: "安全換場與收尾手", p: "安全換場是先發不利時換進來的第二隻，核心是面對任何對手都不會大輸的泛用性。收尾手是最後留下、無護盾也能終結對手的寶可夢，需要高耐久與高威力招式。隊伍通常以「先發 – 安全換場 – 收尾手」三個角色組成，三隻要互相覆蓋彼此的剋星。" },
        { h: "換場帶來的能量・對位優勢", p: "我方換進的寶可夢擊倒對手後，對手必須派出下一隻，而我方寶可夢帶著能量迎戰。這種「帶著能量迎接對手新寶可夢」的狀態稱為能量優勢；對手被迫換場、對面整理成對我方有利的狀態稱為對位（alignment）優勢。省下 2 面護盾的理由，最終也是為了創造這種對位。" },
        { h: "被迫換場的情況", p: "對手換上剋制我方先發的寶可夢時，我方必須選擇 ① 留下並使用護盾 ② 換成我方安全換場。此時對手的 60 秒計時正在跑，若我現在換場，對手 60 秒內無法躲開我的新寶可夢。反之，若我先換場且計時中，對手換上剋星，我就會被「困住」60 秒，只能靠護盾撐住。" },
        { h: "計時結束前該做的事", p: "換場後的 60 秒比想像中長。期間 ① 盡量拔掉對手護盾 ② 盡量累積我方能量 ③ 計時結束瞬間再換上有利的寶可夢，是最理想的做法。特別是在對手即將丟特殊招式前換場，該招式會打在新上場的寶可夢上，可用抵抗屬性「換場吸收」。" },
        { h: "實戰檢查清單", p: "① 對手換場了嗎？是的話對手 60 秒內逃不掉。② 我的計時在跑嗎？是的話無法換場，用護盾與能量撐住。③ 我的下一隻能同時應付當前對手與其後方的對手嗎？④ 能預測對手最後一隻嗎（聯盟實測環境常見組合）？每次換場前自問這四點，失誤會大幅減少。" },
        { h: "練習訣竅", p: "在強度表確認先發・安全換場・收尾手適性高的寶可夢，並用模擬器的隊伍建構檢查我方 3 隻對環境上位對手的覆蓋率。回顧對戰紀錄思考「若不換場會如何」也是很好的訓練。" },
      ],
    },
  },

  "buffs-debuffs": {
    updated: "2026-09-12",
    keywords: {
      ko: ["포켓몬고 버프 기술", "GBL 디버프", "능력치 변화 기술", "포켓몬고 방어 하락 기술", "PvP 버프 확률", "능력치 단계"],
      en: ["Pokémon GO buff moves", "GBL debuff", "stat stage Pokémon GO", "self-debuff moves PvP", "buff chance GBL"],
      ja: ["ポケモンGO バフ わざ", "GBL デバフ", "能力ランク ポケモンGO", "自傷デバフ PvP", "バフ確率 GBL"],
      "zh-TW": ["寶可夢GO 增益招式", "GBL 減益", "能力等級 寶可夢GO", "自身減益招式 PvP", "增益機率 GBL"],
    },
    ko: {
      title: "GBL 버프·디버프 기술 완전 정리 — 능력치 단계와 확률의 실전 활용",
      desc: "포켓몬 GO 배틀리그의 능력치 변화(버프·디버프)는 실드로 막히지 않는 유일한 효과입니다. 단계별 배율 계산, 확정 효과와 확률 효과, 자기 디버프 기술의 운용, 상대 버프에 대응하는 법을 정리했습니다.",
      sections: [
        { p: "많은 차지 기술에는 데미지 외에 '능력치 변화'가 붙어 있습니다. 내 공격을 올리거나, 상대 방어를 내리거나, 반대로 내 방어를 깎는 대가로 위력을 높이는 식입니다. 이 효과는 상대가 실드로 데미지를 막아도 그대로 적용되기 때문에 GBL에서 매우 강력하고, 그래서 정확히 이해할 가치가 있습니다." },
        { h: "능력치 단계와 배율", p: "공격·방어에는 −4에서 +4까지 단계가 있고, 배율은 4를 기준으로 계산합니다. +1은 5/4(×1.25), +2는 6/4(×1.5), +3은 7/4(×1.75), +4는 8/4(×2)입니다. 하락은 −1이 4/5(×0.8), −2가 4/6(×0.667), −3이 4/7(×0.571), −4가 4/8(×0.5)입니다. 상승은 더할수록 효과가 커지고, 하락은 첫 단계가 가장 큰 폭이라는 점이 중요합니다. 단계는 그 포켓몬이 교체되거나 쓰러질 때까지 유지되며 교체해 나갔다가 돌아오면 초기화됩니다." },
        { h: "확정 효과와 확률 효과", p: "능력치 변화에는 100% 발동하는 확정 효과와 12.5%·30%·50% 등으로 발동하는 확률 효과가 있습니다. 확정 효과는 계산이 가능하므로 시뮬레이션과 실전이 일치합니다. 확률 효과는 시뮬레이터가 기댓값으로만 다루므로, 실전에서는 '발동하면 이기고 안 하면 진다'는 도박 매치업이 생깁니다. 자기 능력을 크게 올리는 저확률 기술은 발동 시 게임을 뒤집지만, 그것을 전제로 파티를 짜면 안정성이 떨어집니다." },
        { h: "자기 버프 기술 운용", p: "자기 공격을 올리는 기술은 오래 살아남을수록 가치가 커집니다. 따라서 실드가 있는 상황이나 상대가 실드를 다 쓴 후반에 쓰면 이후 모든 빠른·차지 기술이 강화되어 눈덩이처럼 이득이 쌓입니다. 반대로 곧 쓰러질 포켓몬이 버프 기술을 쓰는 것은 낭비이므로, 그때는 즉시 데미지가 큰 기술을 고르는 편이 낫습니다. 상대 입장에서는 버프가 쌓이기 전에 교체하거나 빨리 잡는 것이 대응책입니다." },
        { h: "상대 디버프 기술 운용", p: "상대 방어나 공격을 내리는 기술은 실드 여부와 무관하게 확정으로 들어가므로 실드를 낭비시키는 효과가 있습니다. 상대가 실드를 쓰면 데미지는 막았지만 능력치는 깎였고, 안 쓰면 데미지와 디버프를 모두 맞습니다. 특히 상대 공격을 내리는 기술은 이후 내가 받는 모든 데미지를 줄여 실질적으로 실드 한 장 가치를 냅니다. 이런 기술을 가진 포켓몬은 선봉으로 세워 상대의 첫 실드를 '손해 보는 실드'로 만드는 운용이 강합니다." },
        { h: "자기 디버프 기술(고위력·대가 지불형)", p: "일부 기술은 사용 후 자기 공격이나 방어를 내리는 대신 위력이 매우 높습니다. 이런 기술은 '마지막 한 방' 또는 '상대가 실드를 다 썼을 때'에 가장 잘 맞습니다. 첫 번째 사용은 강하지만, 두 번째부터는 하락한 능력치 때문에 효율이 급격히 떨어지므로 연속 사용은 피하고, 사용 후에는 교체해 능력치를 초기화하는 운용이 정석입니다. 상대가 이런 기술을 쓴 뒤라면 그 포켓몬을 상대로 공세를 펴기 좋은 타이밍입니다." },
        { h: "능력치 변화와 CMP·브레이크포인트", p: "공격 단계가 바뀌면 동시 차징 우선권(CMP)에 쓰이는 공격 실능력치도 바뀝니다. 즉 상대 공격을 한 단계만 내려도 미러전에서 내가 선공을 얻을 수 있고, 반대로 내 공격이 오르면 원래 못 넘던 빠른 기술 브레이크포인트를 넘어 한 대당 데미지가 오릅니다. 티어표에서 같은 포켓몬이 두 기술배치로 나뉘는 경우가 많은데, 그 차이는 대개 '버프·디버프 기술을 넣느냐 순수 데미지 기술을 넣느냐'입니다." },
        { h: "실전 대응 요령", p: "① 상대 포켓몬의 차지 기술에 능력치 변화가 있는지 미리 알아두기(포켓몬 상세 페이지의 기술 정보). ② 상대 버프가 +2 이상 쌓이면 실드로 버티기보다 교체·정리하기. ③ 내 디버프 기술은 상대 실드가 남아 있을 때 던져 실드를 '손해 보는 실드'로 만들기. ④ 확률 효과는 기대하지 말고 발동하면 보너스로 여기기. ⑤ 능력치가 크게 깎인 내 포켓몬은 교체해 초기화하기." },
      ],
    },
    en: {
      title: "GBL Buffs and Debuffs Explained — Stat Stages, Odds and How to Play Them",
      desc: "Stat changes are the one effect in the Go Battle League that shields cannot stop. Stage multipliers, guaranteed versus chance-based effects, how to run self-debuffing nukes, and how to answer an opponent's buffs.",
      sections: [
        { p: "Many Charged Attacks carry a stat change on top of their damage: raise your Attack, lower the opponent's Defense, or trade your own Defense for a bigger hit. Because these changes apply even when the opponent shields the damage, they are among the strongest effects in GBL and worth understanding precisely." },
        { h: "Stat stages and multipliers", p: "Attack and Defense have stages from −4 to +4, calculated with a base of 4. +1 is 5/4 (×1.25), +2 is 6/4 (×1.5), +3 is 7/4 (×1.75), +4 is 8/4 (×2). Drops are −1 = 4/5 (×0.8), −2 = 4/6 (×0.667), −3 = 4/7 (×0.571), −4 = 4/8 (×0.5). Buffs grow stronger as they stack, while the first drop is the biggest. Stages last until that Pokémon switches out or faints, and reset if it leaves and returns." },
        { h: "Guaranteed versus chance-based effects", p: "Some stat changes always trigger; others fire at 12.5%, 30% or 50%. Guaranteed effects are predictable, so simulations match real play. Chance effects are treated as expected value in a simulator, which creates coin-flip matchups in practice: land the buff and you win, miss it and you lose. Low-odds self-buff moves can flip games, but building a team around them costs consistency." },
        { h: "Running self-buff moves", p: "A move that raises your own Attack is worth more the longer you survive. Use it while you still have shields or after the opponent has spent theirs, and every fast and Charged Attack afterwards snowballs. A Pokémon about to faint should not waste a throw on a buff; pick the move with the most immediate damage instead. The counterplay is to switch out or close the Pokémon out before the buffs stack." },
        { h: "Running debuffs on the opponent", p: "Moves that lower the opponent's Defense or Attack apply whether or not they shield, which makes their shields less valuable. If they shield, they block the damage but still lose stats; if they don't, they take both. Lowering the opponent's Attack reduces all incoming damage afterwards, which is roughly worth a shield. Pokémon with such moves make strong leads because they turn the opponent's first shield into a losing trade." },
        { h: "Self-debuff nukes", p: "Some moves drop your own Attack or Defense after use in exchange for very high power. They are best as a finishing blow or once the opponent is out of shields. The first use is strong, but the second is far weaker because of the drop, so avoid back-to-back throws and switch out afterwards to reset. If the opponent has just used one of these, it is a good moment to go on the offensive against that Pokémon." },
        { h: "Stat changes, CMP and breakpoints", p: "Changing an Attack stage also changes the effective Attack used for Charged Move Priority (CMP). Dropping the opponent's Attack by a single stage can hand you the first throw in a mirror, and raising your own Attack can push a fast move past a breakpoint for extra damage per hit. Many Pokémon appear twice in the tier list with different movesets; the difference is usually whether they run a buff/debuff move or a pure damage move." },
        { h: "Practical checklist", p: "① Know in advance which of the opponent's Charged Attacks carry stat changes (see each Pokémon's detail page). ② Once an opponent's buffs reach +2, switch or close them out rather than tanking with shields. ③ Throw your debuff moves while they still have shields to make those shields a bad trade. ④ Treat chance-based effects as a bonus, never as the plan. ⑤ Switch out a heavily debuffed Pokémon to reset its stats." },
      ],
    },
    ja: {
      title: "GBLのバフ・デバフわざ完全整理 — 能力ランクと確率の実戦活用",
      desc: "ポケモンGOバトルリーグの能力変化（バフ・デバフ）はシールドで防げない唯一の効果です。ランク別倍率の計算、確定効果と確率効果、自己デバフわざの運用、相手のバフへの対応をまとめました。",
      sections: [
        { p: "多くのゲージわざにはダメージのほかに「能力変化」が付いています。自分の攻撃を上げる、相手の防御を下げる、逆に自分の防御を削る代わりに威力を高める、といった具合です。この効果は相手がシールドでダメージを防いでもそのまま適用されるため、GBLでは非常に強力で、正確に理解する価値があります。" },
        { h: "能力ランクと倍率", p: "攻撃・防御には−4から+4までのランクがあり、倍率は4を基準に計算します。+1は5/4（×1.25）、+2は6/4（×1.5）、+3は7/4（×1.75）、+4は8/4（×2）です。下降は−1が4/5（×0.8）、−2が4/6（×0.667）、−3が4/7（×0.571）、−4が4/8（×0.5）です。上昇は重ねるほど効果が大きくなり、下降は最初の1段階が最も大きいという点が重要です。ランクはそのポケモンが交代または倒れるまで維持され、交代して戻ると初期化されます。" },
        { h: "確定効果と確率効果", p: "能力変化には100%発動する確定効果と、12.5%・30%・50%などで発動する確率効果があります。確定効果は計算できるためシミュレーションと実戦が一致します。確率効果はシミュレーターが期待値でしか扱わないため、実戦では「発動すれば勝ち、しなければ負け」のギャンブル対面が生まれます。自分の能力を大きく上げる低確率わざは発動すれば試合を覆しますが、それを前提にパーティを組むと安定性が落ちます。" },
        { h: "自己バフわざの運用", p: "自分の攻撃を上げるわざは長く生き残るほど価値が上がります。したがってシールドがある状況や、相手がシールドを使い切った後半に使えば、以後のすべての通常・ゲージわざが強化され雪だるま式に利益が積み上がります。逆にまもなく倒れるポケモンがバフわざを使うのは無駄なので、その場合は即時ダメージの大きいわざを選ぶほうがよいです。相手側の対策は、バフが積まれる前に交代するか素早く倒すことです。" },
        { h: "相手デバフわざの運用", p: "相手の防御や攻撃を下げるわざはシールドの有無に関係なく確定で入るため、シールドを無駄にさせる効果があります。相手がシールドを使えばダメージは防げても能力は削られ、使わなければダメージとデバフの両方を受けます。特に相手の攻撃を下げるわざは以後自分が受ける全ダメージを減らすため、実質シールド1枚分の価値があります。こうしたわざを持つポケモンは先発に置いて相手の最初のシールドを「損なシールド」にする運用が強いです。" },
        { h: "自己デバフわざ（高威力・代償型）", p: "一部のわざは使用後に自分の攻撃や防御が下がる代わりに威力が非常に高いです。こうしたわざは「最後の一撃」または「相手がシールドを使い切ったとき」に最もよく刺さります。1回目は強力ですが、2回目からは下がった能力のため効率が急激に落ちるので連続使用は避け、使用後は交代して能力を初期化する運用が定石です。相手がこうしたわざを使った後なら、そのポケモンに対して攻勢に出る好機です。" },
        { h: "能力変化とCMP・ブレイクポイント", p: "攻撃ランクが変わると、同時ゲージの優先権（CMP）に使われる攻撃実数値も変わります。つまり相手の攻撃を1段階下げるだけでミラー戦で先手を取れることがあり、逆に自分の攻撃が上がれば本来越えられなかった通常わざのブレイクポイントを越えて1発あたりのダメージが上がります。ティア表で同じポケモンが2つの技構成に分かれていることが多いですが、その違いはたいてい「バフ・デバフわざを入れるか純粋なダメージわざを入れるか」です。" },
        { h: "実戦の対応要領", p: "①相手ポケモンのゲージわざに能力変化があるか事前に把握する（ポケモン詳細ページのわざ情報）。②相手のバフが+2以上積まれたらシールドで耐えるより交代・処理する。③自分のデバフわざは相手のシールドが残っているうちに撃ってシールドを「損なシールド」にする。④確率効果は期待せず、発動したらボーナスと考える。⑤能力が大きく削られた自分のポケモンは交代して初期化する。" },
      ],
    },
    "zh-TW": {
      title: "GBL 增益・減益招式完整整理 — 能力等級與機率的實戰運用",
      desc: "寶可夢 GO 對戰聯盟的能力變化（增益・減益）是唯一無法被護盾阻擋的效果。整理各等級倍率計算、確定效果與機率效果、自身減益招式的運用，以及應對對手增益的方法。",
      sections: [
        { p: "許多特殊招式除了傷害還附帶「能力變化」：提高自身攻擊、降低對手防禦，或以削減自身防禦為代價換取高威力。這些效果即使對手用護盾擋下傷害仍會生效，因此在 GBL 中非常強大，值得精確理解。" },
        { h: "能力等級與倍率", p: "攻擊・防禦有 −4 到 +4 的等級，倍率以 4 為基準計算。+1 為 5/4（×1.25）、+2 為 6/4（×1.5）、+3 為 7/4（×1.75）、+4 為 8/4（×2）。下降則 −1 為 4/5（×0.8）、−2 為 4/6（×0.667）、−3 為 4/7（×0.571）、−4 為 4/8（×0.5）。重點是上升越疊效果越大，下降則第一級幅度最大。等級會持續到該寶可夢換場或倒下為止，換出再換回則重置。" },
        { h: "確定效果與機率效果", p: "能力變化分為 100% 發動的確定效果，以及 12.5%・30%・50% 等機率發動的效果。確定效果可以計算，模擬與實戰一致。機率效果在模擬器中只以期望值處理，實戰中會出現「發動就贏、不發動就輸」的賭博對面。大幅提升自身能力的低機率招式一旦發動能翻盤，但以此為前提組隊會降低穩定性。" },
        { h: "自身增益招式的運用", p: "提高自身攻擊的招式，存活越久價值越高。因此在還有護盾、或對手用完護盾的後期使用，之後所有一般・特殊招式都會強化，收益像滾雪球般累積。反之即將倒下的寶可夢使用增益招式是浪費，此時應選擇即時傷害最高的招式。對手的應對方式則是在增益疊加前換場或快速擊倒。" },
        { h: "對手減益招式的運用", p: "降低對手防禦或攻擊的招式無論是否開盾都確定生效，能讓對手的護盾變得不划算。對手開盾雖擋下傷害但能力仍被削減；不開盾則傷害與減益都吃下。特別是降低對手攻擊的招式，會減少之後我方受到的所有傷害，實質上等於一面護盾的價值。擁有這類招式的寶可夢適合作為先發，把對手的第一面護盾變成「吃虧的護盾」。" },
        { h: "自身減益招式（高威力・付出代價型）", p: "部分招式使用後自身攻擊或防禦會下降，但威力極高。這類招式最適合當「最後一擊」或「對手用完護盾時」使用。第一次很強，但第二次起因能力下降效率驟減，應避免連續使用，用完後換場重置能力是標準做法。若對手剛用過這類招式，正是對該寶可夢發動攻勢的好時機。" },
        { h: "能力變化與 CMP・突破點", p: "攻擊等級改變時，同時特殊招式優先權（CMP）所用的攻擊實際值也會改變。也就是說只要降低對手攻擊一級，鏡像對戰中我方就可能取得先手；反之我方攻擊上升，原本無法跨越的一般招式突破點就能跨過，每一擊傷害提高。強度表中同一隻寶可夢常分成兩種配招，差異多半就是「帶增益・減益招式還是純傷害招式」。" },
        { h: "實戰應對要領", p: "① 事先了解對手寶可夢的特殊招式是否有能力變化（寶可夢詳細頁面的招式資訊）。② 對手增益疊到 +2 以上時，與其用護盾硬撐不如換場・處理掉。③ 我方減益招式在對手還有護盾時丟出，讓護盾變成「吃虧的護盾」。④ 機率效果不要期待，發動了當作紅利。⑤ 能力被大幅削減的我方寶可夢換場重置。" },
      ],
    },
  },

  "rank-and-rating": {
    updated: "2026-09-12",
    keywords: {
      ko: ["포켓몬고 GBL 랭크", "배틀리그 레이팅", "GBL 레전드 3000", "GBL 에이스 베테랑 엑스퍼트", "배틀리그 세트", "GBL 랭크 올리는 법"],
      en: ["Pokémon GO GBL ranks", "GBL rating explained", "GBL Legend 3000", "Ace Veteran Expert rank", "GBL sets per day", "how to rank up GBL"],
      ja: ["ポケモンGO GBL ランク", "バトルリーグ レート", "GBL レジェンド 3000", "エース ベテラン エキスパート", "バトルリーグ セット", "GBL ランク 上げ方"],
      "zh-TW": ["寶可夢GO GBL 段位", "對戰聯盟 分數", "GBL 傳奇 3000", "王牌 老手 專家", "對戰聯盟 組數", "GBL 升段"],
    },
    ko: {
      title: "GBL 랭크·레이팅 시스템 완전 정리 — 랭크 20, 에이스 2000, 레전드 3000까지",
      desc: "포켓몬 GO 배틀리그의 랭크 1~20과 그 위의 에이스·베테랑·엑스퍼트·레전드 등급, 레이팅이 오르내리는 원리, 세트와 하루 배틀 수, 매칭 방식, 시즌 리셋과 보상 구조, 랭크를 올리는 현실적인 방법을 정리했습니다.",
      sections: [
        { p: "GBL을 처음 시작하면 '랭크'와 '레이팅'이라는 두 숫자를 만나게 됩니다. 둘은 다른 개념입니다. 랭크는 시즌 동안 누적으로 올라가는 단계이고, 레이팅은 실력을 나타내는 점수로 이기면 오르고 지면 내려갑니다. 이 글은 두 숫자의 규칙과, 그 규칙을 알고 나면 달라지는 플레이 방식을 설명합니다." },
        { h: "랭크 1~20: 승수로 올라가는 구간", p: "랭크 1부터 20까지는 배틀에서 이긴 횟수(및 배틀 횟수)를 채우면 올라갑니다. 레이팅과 무관하므로 실력에 상관없이 꾸준히 배틀하면 누구나 랭크 20에 도달할 수 있습니다. 랭크가 오를수록 필요한 승수가 늘어나며, 이 구간의 보상(포켓몬 조우·별의모래·이상한 사탕 등)은 랭크에 따라 커집니다. 즉 랭크 20까지는 '얼마나 많이 했는가'의 구간입니다." },
        { h: "레이팅 등급: 에이스·베테랑·엑스퍼트·레전드", p: "랭크 20 위로는 레이팅으로만 올라갑니다. 에이스 2000, 베테랑 2500, 엑스퍼트 2750, 레전드 3000이 기준 점수이며, 각 등급에 도달하면 시즌 중 그 등급 아래로 떨어져도 도달 기록은 유지됩니다. 레전드는 상위 극소수만 도달하는 등급으로, 시즌 종료 보상과 프로필 뱃지의 최고 단계입니다. 에이스가 '기본기를 갖춘 플레이어', 베테랑이 '메타를 이해한 플레이어', 엑스퍼트 이상이 '카운터 플레이와 파티 구성을 최적화한 플레이어'로 흔히 구분됩니다." },
        { h: "레이팅이 오르내리는 원리", p: "레이팅은 상대와의 점수 차이에 따라 변동 폭이 달라지는 방식입니다. 나보다 높은 상대를 이기면 많이 오르고, 낮은 상대에게 지면 많이 내려갑니다. 비슷한 상대끼리는 대략 승패 1번에 ±10~20점 안팎이 일반적입니다. 그래서 레이팅은 단기 승률보다 '지금 내 실력대에서 반 이상 이기는가'로 움직입니다. 5연승·5연패는 흔한 분산이므로 하루 결과에 일희일비할 필요는 없습니다." },
        { h: "세트와 하루 배틀 수", p: "배틀은 5판이 한 세트이며 하루에 여러 세트를 할 수 있고, 세트마다 승수에 따라 보상이 달라집니다. 프리미엄 배틀 패스를 쓰면 같은 세트에서 보상이 좋아지지만 레이팅 계산은 동일합니다. 세트 도중 그만두면 해당 세트는 진행 중으로 남습니다. 하루 배틀 수에는 한도가 있으므로, 랭크를 빠르게 올리려면 매일 세트를 소화하는 꾸준함이 필요합니다." },
        { h: "매칭 방식과 '레이팅 사수'", p: "매칭은 레이팅이 비슷한 상대와 잡힙니다. 그래서 랭크 20 도달 전(레이팅과 무관하게 올라가는 구간)에는 상대 실력 편차가 크고, 레이팅 구간에 들어가면 점점 나와 비슷한 상대만 만나 승률이 50%에 수렴합니다. 이 시점부터 '내가 무엇을 잘못했나'가 랭크를 결정합니다. 시즌 막판에 목표 등급을 넘겼다면 배틀을 멈춰 등급을 지키는 것이 흔한 전략이지만, 등급 도달 기록 자체는 유지되므로 도전을 계속해도 도달 보상은 잃지 않습니다." },
        { h: "시즌 리셋과 보상", p: "시즌이 바뀌면 랭크가 초기화되고, 레이팅은 이전 시즌 값을 기준으로 재조정됩니다. 시즌 종료 시 시즌 중 도달한 최고 등급을 기준으로 보상(별의모래·엘리트 TM 등)이 지급되고, 각 시즌마다 랭크 보상 포켓몬과 아바타 아이템이 바뀝니다. 그래서 시즌 시작 직후는 상대 랭크가 낮아 매칭이 넓은 대신 승수를 쌓기 좋고, 시즌 중반 이후는 실력대별로 정리되어 레이팅 싸움이 됩니다." },
        { h: "랭크를 올리는 현실적인 순서", p: "① 랭크 20까지는 승수가 전부이므로 매일 세트를 채운다. ② 레이팅 구간에 들어가면 지금 리그의 실측 메타(자주 만나는 상대)를 보고 그 상대들에게 지지 않는 파티를 짠다. ③ 실드·교체·베이팅 판단을 배틀 로그로 복기한다. ④ 리그 로테이션(시즌 일정)을 보고 내가 강한 리그가 열리는 주에 배틀을 몰아서 한다. ⑤ 연패 중에는 멈춘다 — 레이팅은 감정으로 잃는 경우가 가장 많습니다. 에이스까지는 파티 완성도, 베테랑 이상은 판단력이 좌우합니다." },
      ],
    },
    en: {
      title: "GBL Ranks and Rating Explained — Rank 20, Ace 2000, Legend 3000",
      desc: "How Pokémon GO Battle League ranks 1–20 and the Ace, Veteran, Expert and Legend tiers work, how rating rises and falls, sets and daily battles, matchmaking, season resets and rewards, and a realistic path to climbing.",
      sections: [
        { p: "New GBL players meet two numbers: rank and rating. They are different things. Rank is a cumulative progression over the season; rating is a skill score that goes up with wins and down with losses. This guide explains the rules behind both and how those rules should change the way you play." },
        { h: "Ranks 1–20: the win-count section", p: "Ranks 1 through 20 are earned by accumulating wins (and battles). Rating plays no part, so anyone who keeps battling reaches rank 20 regardless of skill. Each rank needs more wins than the last, and rewards in this section (encounters, Stardust, Rare Candy and more) grow with rank. Up to rank 20 the question is simply how much you play." },
        { h: "Rating tiers: Ace, Veteran, Expert, Legend", p: "Above rank 20 you climb only by rating. The thresholds are Ace 2000, Veteran 2500, Expert 2750 and Legend 3000, and once you reach a tier its record is kept for the season even if your rating later drops below it. Legend is reached by a tiny fraction of players and is the top end-of-season reward and profile badge. A common reading: Ace has the fundamentals, Veteran understands the meta, Expert and above have optimized counter-play and team building." },
        { h: "How rating moves", p: "Rating changes by an amount that depends on the gap between you and your opponent. Beating a higher-rated player gains a lot; losing to a lower-rated one costs a lot. Between similar players a single result usually moves rating by roughly ±10–20. Rating therefore reflects whether you win more than half of your games at your current level, not a hot streak. Five wins or five losses in a row is ordinary variance." },
        { h: "Sets and daily battles", p: "Battles come in sets of five, several sets are available per day, and rewards per set scale with wins. A Premium Battle Pass improves the rewards of a set but does not change the rating math. If you stop mid-set, that set stays open. Because daily battles are capped, fast rank progress depends on playing your sets every day." },
        { h: "Matchmaking and 'sitting on rating'", p: "Matchmaking pairs you with opponents of similar rating. Before rank 20 (where progression ignores rating) the skill spread is wide; once you are in the rating section you meet opponents like yourself and your win rate converges toward 50%. From then on, your mistakes decide your rank. Late in a season, stopping once you cross a tier is a common way to protect it, but since tier records persist you lose nothing by continuing to play." },
        { h: "Season reset and rewards", p: "When a new season starts, ranks reset and rating is readjusted from the previous season. End-of-season rewards (Stardust, Elite TMs and more) are based on the highest tier reached, and each season rotates its rank-reward Pokémon and avatar items. Early in a season opponents' ranks are low and matchmaking is wide, which is the easiest time to bank wins; from mid-season on, players sort by skill and it becomes a rating fight." },
        { h: "A realistic climbing order", p: "① Until rank 20, wins are everything, so complete your sets daily. ② In the rating section, look at the live meta for the current league and build a team that does not lose to the common threats. ③ Review shield, switch and bait decisions in your battle logs. ④ Watch the league rotation (season schedule) and play most during the weeks of your strongest league. ⑤ Stop during a losing streak; rating is lost to tilt more than anything else. Team quality gets you to Ace; judgment gets you past Veteran." },
      ],
    },
    ja: {
      title: "GBLランク・レートシステム完全整理 — ランク20、エース2000、レジェンド3000まで",
      desc: "ポケモンGOバトルリーグのランク1〜20とその上のエース・ベテラン・エキスパート・レジェンド、レートの増減の仕組み、セットと1日の対戦数、マッチング方式、シーズンリセットと報酬、ランクを上げる現実的な方法をまとめました。",
      sections: [
        { p: "GBLを始めると「ランク」と「レート」という2つの数字に出会います。これらは別の概念です。ランクはシーズン中に累積で上がる段階で、レートは実力を示す点数で勝てば上がり負ければ下がります。この記事では両方のルールと、そのルールを知ると変わるプレイ方針を説明します。" },
        { h: "ランク1〜20：勝利数で上がる区間", p: "ランク1から20までは対戦の勝利数（および対戦数）を満たせば上がります。レートとは無関係なので、実力にかかわらず対戦を続ければ誰でもランク20に到達できます。ランクが上がるほど必要な勝利数が増え、この区間の報酬（ポケモンとの遭遇・ほしのすな・ふしぎなアメなど）もランクに応じて増えます。つまりランク20までは「どれだけやったか」の区間です。" },
        { h: "レート階級：エース・ベテラン・エキスパート・レジェンド", p: "ランク20より上はレートでのみ上がります。エース2000、ベテラン2500、エキスパート2750、レジェンド3000が基準点で、各階級に到達するとシーズン中にその階級を下回っても到達記録は維持されます。レジェンドは上位ごく少数だけが到達する階級で、シーズン終了報酬とプロフィールバッジの最高段階です。エースが「基本を備えたプレイヤー」、ベテランが「メタを理解したプレイヤー」、エキスパート以上が「カウンタープレイとパーティ構築を最適化したプレイヤー」と一般に区別されます。" },
        { h: "レートが増減する仕組み", p: "レートは相手との点差によって変動幅が変わる方式です。自分より高い相手に勝てば大きく上がり、低い相手に負ければ大きく下がります。近い相手同士ではおおむね1勝敗で±10〜20点前後が一般的です。そのためレートは短期の勝率より「今の実力帯で半分以上勝てているか」で動きます。5連勝・5連敗はよくある分散なので、1日の結果に一喜一憂する必要はありません。" },
        { h: "セットと1日の対戦数", p: "対戦は5戦で1セット、1日に複数セット行え、セットごとに勝利数に応じて報酬が変わります。プレミアムバトルパスを使うと同じセットで報酬が良くなりますが、レート計算は同じです。セットの途中でやめるとそのセットは進行中のまま残ります。1日の対戦数には上限があるので、ランクを早く上げるには毎日セットを消化する継続が必要です。" },
        { h: "マッチング方式と「レート温存」", p: "マッチングはレートが近い相手と組まれます。そのためランク20到達前（レートと無関係に上がる区間）は相手の実力差が大きく、レート区間に入ると徐々に自分と近い相手ばかりになり勝率は50%に収束します。この時点から「自分が何を間違えたか」がランクを決めます。シーズン終盤に目標階級を越えたら対戦を止めて階級を守るのがよくある戦略ですが、到達記録自体は維持されるので挑戦を続けても到達報酬は失いません。" },
        { h: "シーズンリセットと報酬", p: "シーズンが変わるとランクは初期化され、レートは前シーズンの値を基に再調整されます。シーズン終了時にはシーズン中の最高到達階級を基準に報酬（ほしのすな・すごいわざマシンなど）が付与され、シーズンごとにランク報酬ポケモンとアバターアイテムが変わります。そのためシーズン開始直後は相手のランクが低くマッチングが広い分、勝利数を積みやすく、シーズン中盤以降は実力帯ごとに整理されてレート戦になります。" },
        { h: "ランクを上げる現実的な順序", p: "①ランク20までは勝利数がすべてなので毎日セットを消化する。②レート区間に入ったら今のリーグの実測メタ（よく会う相手）を見て、その相手に負けないパーティを組む。③シールド・交代・ベイトの判断をバトルログで振り返る。④リーグローテーション（シーズン日程）を見て自分の得意リーグが開催される週に対戦を集中させる。⑤連敗中は止める — レートは感情で失うことが最も多いです。エースまではパーティの完成度、ベテラン以上は判断力が左右します。" },
      ],
    },
    "zh-TW": {
      title: "GBL 段位・分數系統完整整理 — 從段位 20、王牌 2000 到傳奇 3000",
      desc: "整理寶可夢 GO 對戰聯盟的段位 1〜20 與其上的王牌・老手・專家・傳奇階級、分數升降原理、組數與每日對戰數、配對方式、賽季重置與獎勵，以及升段的實際方法。",
      sections: [
        { p: "剛開始 GBL 會遇到「段位」和「分數」兩個數字。兩者是不同概念。段位是賽季中累積上升的階段，分數則是代表實力的點數，贏了上升、輸了下降。本文說明兩者的規則，以及了解規則後應改變的打法。" },
        { h: "段位 1〜20：以勝場數上升的區間", p: "段位 1 到 20 只要累積勝場數（及對戰數）就會上升。與分數無關，因此不論實力，持續對戰任何人都能達到段位 20。段位越高所需勝場越多，此區間的獎勵（寶可夢遭遇・星星沙子・神奇糖果等）也隨段位增加。也就是說段位 20 之前是「打了多少」的區間。" },
        { h: "分數階級：王牌・老手・專家・傳奇", p: "段位 20 之上只能靠分數上升。基準分數為王牌 2000、老手 2500、專家 2750、傳奇 3000，達到各階級後，即使賽季中分數跌破，達成紀錄仍會保留。傳奇是極少數頂尖玩家才能達到的階級，也是賽季結束獎勵與個人檔案徽章的最高階。一般認為王牌是「具備基本功的玩家」、老手是「理解環境的玩家」、專家以上則是「將反制打法與隊伍組成最佳化的玩家」。" },
        { h: "分數升降的原理", p: "分數的變動幅度取決於與對手的分差。打贏比自己高分的對手漲得多，輸給低分對手掉得多。實力相近的對手之間，一場勝負通常在 ±10〜20 分左右。因此分數反映的不是短期勝率，而是「在目前的實力帶能否贏超過一半」。5 連勝・5 連敗是常見的波動，不必為一天的結果患得患失。" },
        { h: "組數與每日對戰數", p: "5 場為一組，每天可打多組，每組依勝場數給予不同獎勵。使用高級對戰入場券可提升同一組的獎勵，但分數計算相同。中途停止該組會保持進行中。每日對戰數有上限，想快速升段需要每天把組數打完的持續性。" },
        { h: "配對方式與「守分」", p: "配對會找分數相近的對手。因此段位 20 之前（與分數無關的區間）對手實力差距大，進入分數區間後會逐漸只遇到與自己相近的對手，勝率收斂至 50%。從這時起，「我哪裡做錯了」決定段位。賽季末超過目標階級後停止對戰以保住階級是常見策略，但由於達成紀錄本身會保留，繼續挑戰也不會失去達成獎勵。" },
        { h: "賽季重置與獎勵", p: "賽季更替時段位重置，分數則以上一賽季的數值為基準重新調整。賽季結束時依賽季中達到的最高階級發放獎勵（星星沙子・厲害招式學習器等），每個賽季的段位獎勵寶可夢與造型道具都不同。因此賽季剛開始時對手段位低、配對範圍廣，容易累積勝場；賽季中期以後依實力帶整理完畢，變成分數之爭。" },
        { h: "升段的實際順序", p: "① 段位 20 之前勝場就是一切，每天打完組數。② 進入分數區間後，查看當前聯盟的實測環境（常遇到的對手），組出不會輸給這些對手的隊伍。③ 用對戰紀錄回顧護盾・換場・騙盾的判斷。④ 查看聯盟輪替（賽季日程），在自己擅長的聯盟開放的週集中對戰。⑤ 連敗時就停 —— 分數最常因情緒而流失。到王牌靠隊伍完成度，老手以上靠判斷力。" },
      ],
    },
  },

  "shadow-xl-investment": {
    updated: "2026-09-12",
    keywords: {
      ko: ["포켓몬고 그림자 포켓몬 PvP", "XL 사탕 슈퍼리그", "포켓몬고 XL 사탕 모으는 법", "베스트버디 PvP", "포켓몬고 육성 우선순위", "그림자 정화"],
      en: ["Shadow Pokémon PvP", "XL Candy Great League", "how to get XL Candy", "Best Buddy PvP boost", "Pokémon GO investment priority", "purify or keep shadow"],
      ja: ["ポケモンGO シャドウ PvP", "XLアメ スーパーリーグ", "XLアメ 集め方", "相棒ブースト PvP", "ポケモンGO 育成 優先順位", "シャドウ リトレーン"],
      "zh-TW": ["寶可夢GO 暗影 PvP", "XL糖果 超級聯盟", "XL糖果 收集", "最佳夥伴 PvP", "寶可夢GO 養成 優先", "暗影 淨化"],
    },
    ko: {
      title: "그림자·XL·베스트버디 — 사탕과 별의모래를 어디에 쓸 것인가",
      desc: "GBL 육성은 자원 배분 문제입니다. 그림자 포켓몬의 공격 1.2배·방어 0.833배가 실전에서 뜻하는 것, 레벨 40→50에 필요한 XL 사탕 296개를 모으는 현실적인 방법, 베스트버디 +1레벨의 조건, 리그별 투자 우선순위를 정리했습니다.",
      sections: [
        { p: "포켓몬을 PvP용으로 완성하려면 별의모래·사탕·XL 사탕·시간이 듭니다. 이 자원은 유한하므로 '무엇을 먼저 키울까'가 '어떻게 싸울까'만큼 중요합니다. 이 글은 그림자·XL·베스트버디라는 세 가지 투자 옵션이 각각 무엇을 주고 무엇을 요구하는지 숫자로 정리합니다." },
        { h: "그림자 포켓몬: 공격 1.2배, 방어 0.833배", p: "그림자 포켓몬은 공격이 20% 오르고 방어는 약 17% 내려갑니다(1.2 × 0.833 ≈ 1). 전체 데미지 교환은 비슷해 보이지만, 실전에서는 두 가지가 달라집니다. 첫째, 공격이 오르면 빠른 기술 데미지가 한 단위 오르는 브레이크포인트를 넘기 쉬워 같은 시간에 더 많은 데미지를 넣습니다. 둘째, 방어가 내려가면 상대의 브레이크포인트에 걸리기 쉬워지고 차지 기술 한 방에 더 크게 흔들립니다. 결과적으로 그림자는 '빨리 죽고 빨리 죽이는' 성격이 되어 실드 지원을 받는 어택커나 선봉에 적합하고, 실드 없이 버텨야 하는 클로저에는 일반 개체가 나은 경우가 많습니다." },
        { h: "그림자의 비용과 제약", p: "그림자 포켓몬은 파워업 별의모래와 사탕이 일반의 1.2배 듭니다. 기본 차지 기술 '분노(원한)'는 일반 기술머신으로 바꿀 수 없고 GO 로켓단 이벤트 기간에만 교체할 수 있으므로, 이벤트 일정을 확인해 그때 기술을 바꿔 두어야 합니다. 정화하면 그림자 보정이 사라지고 개체값이 각 +2 되며 파워업 비용이 줄어들지만, PvP에서는 대개 그림자 상태가 더 가치 있으므로 정화는 신중해야 합니다. 어느 쪽이 나은지는 티어표에서 같은 종의 그림자·일반 순위를 비교해 결정하세요." },
        { h: "XL 사탕: 레벨 40에서 50까지 296개", p: "레벨 40을 넘기려면 XL 사탕이 필요하며, 40→50까지 총 296개(레벨 구간별 10·12·15·17·20개씩)가 듭니다. 슈퍼리그 주력 중 종족값이 낮은 포켓몬(마릴리·누오·매지컬리프 등)은 레벨 45~50에서 CP 1500이 되므로 XL이 필수이고, 하이퍼리그는 더 많은 종이 XL을 요구합니다. 반대로 종족값이 높은 포켓몬은 레벨 40 이전에 CP 상한에 닿아 XL이 필요 없습니다. IV 순위 체커의 '레벨' 열이 40을 넘는지 확인하는 것이 투자 판단의 첫 단계입니다." },
        { h: "XL 사탕 모으는 현실적인 방법", p: "① 포획: 트레이너 레벨 31 이상이면 포획 시 XL이 드롭되며, 포획한 포켓몬의 레벨이 높을수록 확률이 오릅니다. 커뮤니티 데이·스포트라이트 아워의 대량 포획이 가장 효율적입니다. ② 교환: 교환 시 XL을 받을 확률이 있고, 거리가 멀수록 유리합니다. ③ 파트너 걷기: 파트너로 걸으면 XL을 받을 수 있습니다. ④ 변환: 일반 사탕 100개로 XL 1개를 만들 수 있지만 매우 비쌉니다. ⑤ 희귀 XL 사탕: 레이드·리서치·GBL 보상으로 얻는 만능 XL은 마스터리그 전설에 아껴 쓰세요. 결론적으로 XL이 필요한 슈퍼리그 주력은 '대량 포획이 가능한 종'을 우선하는 것이 현실적입니다." },
        { h: "베스트버디 +1레벨의 조건", p: "베스트버디(파트너 레벨 최고 단계)로 만든 포켓몬은 배틀 중 레벨이 1 오르며(마스터리그는 51까지), CP 상한을 넘지 않는 범위에서 스탯이 올라갑니다. 효과를 받으려면 그날 파트너와 놀아 '기분 최고' 상태여야 하고, 파트너로 설정된 포켓몬만 적용됩니다. 그래서 세 마리 모두에게 줄 수는 없고, 한 마리만 골라야 합니다. 마스터리그에서는 레벨 51이 종종 CMP 우선권과 브레이크포인트를 바꾸므로 주력 한 마리에 확실히 투자하고, CP 캡이 있는 리그에서는 베스트버디 시 순위 1위 개체가 달라지므로 IV 체커에서 옵션을 켜고 확인하세요." },
        { h: "리그별 투자 우선순위", p: "슈퍼리그: 사탕·모래 부담이 가장 적지만 XL이 필요한 종이 많으므로, 먼저 XL 불필요 종(레벨 40 이하에서 캡)으로 파티를 완성하고 XL 종은 한 마리씩 늘려갑니다. 하이퍼리그: 레벨 40~50 구간의 XL 요구가 많아 비용이 가장 큽니다. 실측 메타에서 오래 살아남는 종만 투자하세요. 마스터리그: 전설 포켓몬 레벨 50 + XL 296개 + 베스트버디가 표준이라 가장 비쌉니다. 한 마리를 완성하는 데 수개월이 걸릴 수 있으니, 시즌이 바뀌어도 살아남는 범용 종(티어표에서 여러 시즌 상위)에 먼저 투자하세요." },
        { h: "투자 전 체크리스트", p: "① 티어표에서 이 포켓몬이 S/A 티어인가, 실측 메타에서도 자주 나오는가. ② IV 체커에서 필요한 레벨이 40을 넘는가(넘으면 XL 296개 계산). ③ 그림자 개체를 쓸 경우 '분노' 교체 이벤트 일정이 언제인가. ④ 베스트버디로 만들 한 마리는 정해졌는가. ⑤ 다음 시즌 리그 로테이션에서 이 리그가 얼마나 열리는가. 다섯 개 중 세 개 이상 '예'가 아니면, 지금 있는 개체로 먼저 쓰고 투자는 미루는 편이 자원을 아끼는 길입니다." },
      ],
    },
    en: {
      title: "Shadow, XL and Best Buddy — Where to Spend Candy and Stardust",
      desc: "Building for GBL is a resource-allocation problem. What Shadow Pokémon's 1.2× Attack and 0.833× Defense mean in practice, a realistic way to gather the 296 XL Candy needed for level 40 to 50, the conditions for the Best Buddy +1 level, and investment priorities by league.",
      sections: [
        { p: "Finishing a Pokémon for PvP costs Stardust, Candy, XL Candy and time. Those resources are finite, so deciding what to build first matters as much as how you battle. This guide puts numbers on the three investment options, Shadow, XL and Best Buddy, and what each gives and demands." },
        { h: "Shadow Pokémon: 1.2× Attack, 0.833× Defense", p: "A Shadow Pokémon gains 20% Attack and loses about 17% Defense (1.2 × 0.833 ≈ 1). The overall damage trade looks neutral, but two things change in practice. Higher Attack makes it easier to cross fast-move breakpoints, so it deals more damage in the same time. Lower Defense makes it easier for the opponent to hit their breakpoints and makes each Charged Attack hurt more. Shadows therefore play as 'die fast, kill fast', which suits leads and attackers backed by shields, while a non-shadow is often better as a closer that must hold without shields." },
        { h: "Costs and limits of Shadows", p: "Shadow Pokémon cost 1.2× the Stardust and Candy to power up. Their default Charged Attack, Frustration, cannot be removed with a normal TM and can only be changed during Team GO Rocket events, so check the event calendar and swap it then. Purifying removes the Shadow modifiers, adds +2 to each IV and lowers power-up costs, but for PvP the Shadow form is usually more valuable, so purify with care. Compare the Shadow and regular rankings of the same species in the tier list before deciding." },
        { h: "XL Candy: 296 from level 40 to 50", p: "Going past level 40 requires XL Candy, and level 40 to 50 costs 296 in total (10, 12, 15, 17 and 20 per level across the range). Low-base-stat Great League staples such as Azumarill, Quagsire and Meganium hit CP 1500 around level 45–50, so XL is mandatory, and even more species need XL in Ultra League. High-base-stat Pokémon reach the cap before level 40 and need none. Checking whether the 'Level' column in the IV rank checker exceeds 40 is the first step of any investment decision." },
        { h: "Realistic ways to collect XL Candy", p: "① Catching: from trainer level 31, catches can drop XL, with better odds from higher-level Pokémon. Mass catching on Community Day and Spotlight Hour is the most efficient source. ② Trading: trades can award XL, with better odds over longer distances. ③ Buddy walking: your buddy can find XL as you walk. ④ Conversion: 100 regular Candy makes 1 XL, which is very expensive. ⑤ Rare XL Candy from raids, research and GBL rewards works for any species; save it for Master League Legendaries. The practical rule: for Great League XL projects, favor species you can mass-catch." },
        { h: "Conditions for the Best Buddy +1 level", p: "A Best Buddy gains one level in battle (up to 51 in Master League), raising stats as long as the CP cap allows. The boost requires the buddy to be at Best Buddy level, to have been played with that day so it is in the 'excited' mood, and to be your currently assigned buddy. You cannot give it to all three Pokémon, only one. In Master League level 51 often changes CMP and breakpoints, so invest firmly in one main Pokémon; in capped leagues the rank-1 spread changes with Best Buddy, so check the IV checker with the option on." },
        { h: "Investment priority by league", p: "Great League: cheapest in Candy and Stardust but many species need XL, so first finish a team from species that cap under level 40, then add XL species one at a time. Ultra League: the most expensive per Pokémon because so many need levels 40–50; invest only in species that stay in the live meta. Master League: level 50 Legendaries with 296 XL and a Best Buddy are the standard, so one Pokémon can take months; prioritize species that survive across seasons (top-tier in multiple seasons)." },
        { h: "Pre-investment checklist", p: "① Is it S or A tier and common in the live meta? ② Does the required level exceed 40 (if so, budget 296 XL)? ③ If Shadow, when is the next Rocket event to replace Frustration? ④ Have you chosen the single Pokémon that will be your Best Buddy? ⑤ How often does this league appear in next season's rotation? If fewer than three answers are 'yes', use what you already have and defer the investment." },
      ],
    },
    ja: {
      title: "シャドウ・XL・相棒ブースト — アメとほしのすなをどこに使うか",
      desc: "GBLの育成は資源配分の問題です。シャドウポケモンの攻撃1.2倍・防御0.833倍が実戦で意味すること、レベル40→50に必要なXLアメ296個を集める現実的な方法、相棒ブースト+1レベルの条件、リーグ別の投資優先順位をまとめました。",
      sections: [
        { p: "ポケモンをPvP用に完成させるにはほしのすな・アメ・XLアメ・時間がかかります。これらの資源は有限なので「何を先に育てるか」は「どう戦うか」と同じくらい重要です。この記事はシャドウ・XL・相棒ブーストという3つの投資オプションがそれぞれ何を与え何を要求するかを数字で整理します。" },
        { h: "シャドウポケモン：攻撃1.2倍、防御0.833倍", p: "シャドウポケモンは攻撃が20%上がり、防御は約17%下がります（1.2 × 0.833 ≈ 1）。全体のダメージ交換は同等に見えますが、実戦では2つが変わります。第一に、攻撃が上がると通常わざのダメージが1上がるブレイクポイントを越えやすくなり、同じ時間でより多くのダメージを入れられます。第二に、防御が下がると相手のブレイクポイントにかかりやすくなり、ゲージわざ一発で大きく削られます。結果としてシャドウは「早く倒れ早く倒す」性格になり、シールドに守られるアタッカーや先発に向き、シールドなしで耐えるクローザーには通常個体のほうが良い場合が多いです。" },
        { h: "シャドウのコストと制約", p: "シャドウポケモンは強化のほしのすなとアメが通常の1.2倍かかります。初期ゲージわざ「やつあたり」は通常のわざマシンで変えられず、GOロケット団イベント期間にのみ変更できるため、イベント日程を確認してそのときにわざを変えておく必要があります。リトレーンするとシャドウ補正が消え個体値が各+2され強化コストが下がりますが、PvPではたいていシャドウ状態のほうが価値があるためリトレーンは慎重に。どちらが良いかはティア表で同じ種のシャドウ・通常の順位を比較して決めましょう。" },
        { h: "XLアメ：レベル40から50まで296個", p: "レベル40を超えるにはXLアメが必要で、40→50まで合計296個（レベル帯ごとに10・12・15・17・20個ずつ）かかります。スーパーリーグ主力のうち種族値が低いポケモン（マリルリ・ヌオー・メガニウムなど）はレベル45〜50でCP1500になるためXLが必須で、ハイパーリーグではさらに多くの種がXLを要求します。逆に種族値が高いポケモンはレベル40以前にCP上限に達するためXLは不要です。個体値ランクチェッカーの「レベル」列が40を超えるか確認するのが投資判断の第一段階です。" },
        { h: "XLアメを集める現実的な方法", p: "①捕獲：トレーナーレベル31以上なら捕獲時にXLがドロップし、捕獲したポケモンのレベルが高いほど確率が上がります。コミュニティ・デイやスポットライトアワーの大量捕獲が最も効率的です。②交換：交換時にXLをもらえる確率があり、距離が遠いほど有利です。③相棒と歩く：相棒として歩くとXLをもらえます。④変換：通常のアメ100個でXL1個を作れますが非常に高価です。⑤ふしぎなアメXL：レイド・リサーチ・GBL報酬で得る万能XLはマスターリーグの伝説に温存しましょう。結論として、XLが必要なスーパーリーグ主力は「大量捕獲できる種」を優先するのが現実的です。" },
        { h: "相棒ブースト +1レベルの条件", p: "大親友（相棒レベル最高段階）にしたポケモンはバトル中にレベルが1上がり（マスターリーグは51まで）、CP上限を超えない範囲でステータスが上がります。効果を受けるにはその日に相棒と遊んで「ごきげん最高」状態である必要があり、相棒に設定されたポケモンだけに適用されます。そのため3匹全部には付けられず、1匹だけ選ぶ必要があります。マスターリーグではレベル51がしばしばCMP優先権とブレイクポイントを変えるため主力1匹に確実に投資し、CP上限のあるリーグでは相棒ブースト時に順位1位の個体が変わるので、個体値チェッカーでオプションをオンにして確認してください。" },
        { h: "リーグ別の投資優先順位", p: "スーパーリーグ：アメ・すなの負担は最も少ないがXLが必要な種が多いため、まずXL不要種（レベル40以下で上限到達）でパーティを完成させ、XL種は1匹ずつ増やします。ハイパーリーグ：レベル40〜50帯のXL要求が多くコストが最大です。実測メタで長く残る種だけに投資しましょう。マスターリーグ：伝説のレベル50＋XL296個＋相棒ブーストが標準のため最も高価です。1匹の完成に数か月かかることもあるので、シーズンが変わっても残る汎用種（ティア表で複数シーズン上位）に先に投資してください。" },
        { h: "投資前チェックリスト", p: "①ティア表でこのポケモンはS/Aティアか、実測メタでもよく出るか。②個体値チェッカーで必要レベルが40を超えるか（超えるならXL296個を計算）。③シャドウ個体を使う場合「やつあたり」変更イベントの日程はいつか。④相棒ブーストにする1匹は決まったか。⑤次シーズンのリーグローテーションでこのリーグはどれくらい開催されるか。5つのうち3つ以上が「はい」でなければ、今ある個体でまず使い投資は後回しにするのが資源を節約する道です。" },
      ],
    },
    "zh-TW": {
      title: "暗影・XL・最佳夥伴 —— 糖果與星星沙子該花在哪裡",
      desc: "GBL 養成是資源分配問題。整理暗影寶可夢攻擊 1.2 倍・防禦 0.833 倍在實戰的意義、等級 40→50 所需 296 顆 XL 糖果的實際收集方法、最佳夥伴 +1 等級的條件，以及各聯盟的投資優先順序。",
      sections: [
        { p: "把寶可夢養成 PvP 用需要星星沙子・糖果・XL 糖果與時間。這些資源有限，因此「先養什麼」與「怎麼打」同樣重要。本文以數字整理暗影・XL・最佳夥伴三種投資選項各自給予什麼、要求什麼。" },
        { h: "暗影寶可夢：攻擊 1.2 倍、防禦 0.833 倍", p: "暗影寶可夢攻擊提高 20%，防禦降低約 17%（1.2 × 0.833 ≈ 1）。整體傷害交換看似相近，但實戰中有兩點不同。第一，攻擊提高後更容易跨過一般招式傷害 +1 的突破點，同樣時間內造成更多傷害。第二，防禦降低後更容易被對手跨過突破點，每次特殊招式受創更大。結果暗影呈現「死得快、殺得快」的特性，適合有護盾支援的攻擊手或先發；需無盾撐住的收尾手則通常一般個體更好。" },
        { h: "暗影的成本與限制", p: "暗影寶可夢強化所需星星沙子與糖果為一般的 1.2 倍。預設特殊招式「遷怒」無法用一般招式學習器更換，只能在 GO 火箭隊活動期間更換，因此需確認活動日程並在當時換招。淨化後暗影修正消失、個體值各 +2、強化費用降低，但在 PvP 中通常暗影狀態更有價值，淨化需謹慎。哪個較好請在強度表比較同一物種的暗影與一般排名後決定。" },
        { h: "XL 糖果：從等級 40 到 50 需 296 顆", p: "超過等級 40 需要 XL 糖果，40→50 共需 296 顆（依等級區間每級 10・12・15・17・20 顆）。超級聯盟主力中種族值低的寶可夢（瑪力露麗・沼王・大竺葵等）在 45〜50 級才達 CP 1500，XL 為必需；高級聯盟需要 XL 的物種更多。反之種族值高的寶可夢在 40 級前就達 CP 上限，不需 XL。確認 IV 排名檢查器的「等級」欄是否超過 40，是投資判斷的第一步。" },
        { h: "收集 XL 糖果的實際方法", p: "① 捕捉：訓練家等級 31 以上捕捉時會掉落 XL，捕捉的寶可夢等級越高機率越高。社群日・聚光燈時刻的大量捕捉最有效率。② 交換：交換時有機率獲得 XL，距離越遠越有利。③ 夥伴散步：與夥伴散步可獲得 XL。④ 轉換：100 顆一般糖果可換 1 顆 XL，但非常昂貴。⑤ 神奇糖果 XL：團體戰・調查・GBL 獎勵獲得的萬用 XL 請留給大師聯盟的傳說。結論是需要 XL 的超級聯盟主力，優先選擇「能大量捕捉的物種」較實際。" },
        { h: "最佳夥伴 +1 等級的條件", p: "成為最佳夥伴（夥伴等級最高階）的寶可夢在對戰中等級 +1（大師聯盟最高 51），在不超過 CP 上限的範圍內提高數值。要獲得效果，當天需與夥伴互動達到「心情極佳」狀態，且僅適用於目前設定的夥伴。因此無法給三隻，只能選一隻。大師聯盟中等級 51 常改變 CMP 優先權與突破點，請確實投資在一隻主力；有 CP 上限的聯盟中最佳夥伴會改變排名第 1 的個體，請在 IV 檢查器開啟選項確認。" },
        { h: "各聯盟的投資優先順序", p: "超級聯盟：糖果・沙子負擔最小，但需要 XL 的物種多，先用不需 XL 的物種（40 級以下達上限）完成隊伍，再一隻一隻增加 XL 物種。高級聯盟：40〜50 級區間的 XL 需求多，成本最高，只投資在實測環境中長期存活的物種。大師聯盟：傳說寶可夢 50 級＋296 顆 XL＋最佳夥伴是標配，最昂貴，完成一隻可能需數月，請優先投資跨賽季仍存活的泛用物種（強度表中多個賽季上位）。" },
        { h: "投資前檢查清單", p: "① 在強度表中是 S/A 級且實測環境常見嗎？② IV 檢查器所需等級超過 40 嗎（超過則計算 296 顆 XL）？③ 若用暗影個體，「遷怒」更換活動日程是何時？④ 要設為最佳夥伴的那一隻決定了嗎？⑤ 下賽季聯盟輪替中此聯盟開放多久？五項中若未達三項「是」，先用手上的個體、延後投資才是節省資源之道。" },
      ],
    },
  },

  "raid-basics": {
    updated: "2026-09-12",
    keywords: {
      ko: ["포켓몬고 레이드 하는법", "레이드 입문", "포켓몬고 레이드 등급", "날씨 부스트 레이드", "레이드 100% CP", "메가 레이드 효과", "원격 레이드 패스"],
      en: ["Pokémon GO raid guide", "raid basics", "raid tiers Pokémon GO", "weather boost raid", "raid 100% CP", "Mega raid bonus", "Remote Raid Pass"],
      ja: ["ポケモンGO レイド やり方", "レイド 入門", "レイド ランク", "天候ブースト レイド", "レイド 100%個体 CP", "メガレイド 効果", "リモートレイドパス"],
      "zh-TW": ["寶可夢GO 團體戰 教學", "團體戰 入門", "團體戰 等級", "天氣加成 團體戰", "團體戰 100% CP", "超級進化 團體戰 效果", "遠距團體戰入場券"],
    },
    ko: {
      title: "포켓몬 GO 레이드 입문 — 등급·패스·날씨 부스트·100% CP·메가 보너스",
      desc: "레이드는 포켓몬 GO에서 전설·메가 포켓몬과 강한 딜러를 얻는 핵심 콘텐츠입니다. 레이드 등급별 난이도와 필요 인원, 패스 종류, 포획 레벨 20과 날씨 부스트 25, 100% CP 확인법, 메가진화 보너스, 딜러 파티 구성과 회피, 자주 하는 실수를 정리했습니다.",
      sections: [
        { p: "레이드 배틀은 체육관에 나타난 보스 포켓몬을 여러 트레이너가 함께 공격해 제한 시간 안에 쓰러뜨리고, 성공하면 그 포켓몬을 포획할 기회를 얻는 콘텐츠입니다. 전설 포켓몬, 메가 에너지, 희귀 XL 사탕, 강한 딜러 대부분이 레이드에서 나오므로, PvP·PvE 어느 쪽을 하든 레이드는 피할 수 없습니다." },
        { h: "레이드 등급과 필요 인원", p: "레이드는 1성(혼자 가능), 3성(고레벨이면 혼자, 보통 2~3명), 5성(전설, 보통 4~8명), 메가(3~6명), 그림자 레이드(현장 참여만 가능하며 후반 격노 상태에서 어려워짐), 그리고 특별 등급(엘리트·프라이멀 등)으로 나뉩니다. 필요 인원은 참가자 레벨과 딜러 준비 상태, 날씨, 보스 타입에 따라 크게 달라지므로, 딜러 티어표의 추천 공격수를 6마리 채워 가는 것이 인원을 줄이는 가장 확실한 방법입니다." },
        { h: "레이드 패스 종류", p: "무료 레이드 패스는 체육관 포토디스크를 돌려 하루 1장 받으며(최대 보유 제한), 프리미엄 배틀 패스는 상점에서 구매해 현장 레이드에 씁니다. 원격 레이드 패스는 멀리 있는 레이드에 참여할 수 있지만 하루 사용 제한과 가격이 있고, 그림자 레이드처럼 원격이 불가능한 레이드도 있습니다. 레이드 초대 기능으로 친구를 원격 참여시킬 수 있어 지역 커뮤니티 없이도 5성 레이드를 깰 수 있습니다." },
        { h: "포획 레벨 20, 날씨 부스트 25", p: "레이드에서 잡는 포켓몬은 레벨 20으로 고정되며 개체값 하한은 10/10/10입니다. 그 보스의 타입에 맞는 날씨(예: 불꽃 타입에 맑음)가 적용되면 레벨 25로 잡히고 CP가 오르며 사탕도 추가됩니다. 그래서 같은 보스라도 날씨 부스트 상태의 개체는 파워업 비용을 아끼는 셈이 됩니다. 반면 PvP용 저공격 개체는 레이드에서 얻기 어렵고(하한 10), 마스터리그용 고IV는 레이드가 최적입니다." },
        { h: "100% CP 확인법", p: "포획 화면의 CP로 개체값을 짐작할 수 있습니다. 15/15/15 개체는 레벨 20에서 정해진 CP(예: 보스마다 다름)가 나오고, 날씨 부스트 시 레벨 25 CP로 바뀝니다. GBL Note의 '보스 100% CP' 페이지는 이달 보스의 일반·날씨 부스트 100% CP와 개체값별 CP표를 제공하므로, 포획 전에 확인해 두면 잡자마자 개체값을 알 수 있습니다. 보통 15/15/15 외에 공격 15에 방어·체력 14~15인 개체도 레이드·마스터리그 용도로 충분합니다." },
        { h: "메가진화 보너스", p: "메가진화 포켓몬이 레이드에 참여하면, 그 메가와 같은 타입 기술을 쓰는 모든 참가자의 공격이 강화되고, 레이드 후 포획 시 같은 타입 포켓몬의 사탕이 추가됩니다. 메가 레벨이 오를수록 보너스가 커지고 XL 사탕 확률도 붙습니다. 따라서 보스 약점 타입의 메가 한 마리를 파티에 넣는 것이 인원을 줄이는 가장 효율적인 방법입니다. 단, 여러 명이 같은 메가를 넣어도 보너스는 중복되지 않으므로 파티원끼리 다른 타입 메가를 나누는 편이 좋습니다." },
        { h: "딜러 파티 구성과 회피", p: "파티 6마리는 보스 약점을 찌르는 타입으로 채우고, 빠른 기술과 차지 기술이 모두 그 타입이어야 DPS가 나옵니다. 종족값이 높아도 기술이 맞지 않으면 딜이 크게 떨어집니다. 회피(화면 스와이프)는 보스 차지 기술 데미지를 줄이지만 그 사이 딜을 못 넣으므로, 인원이 충분하면 회피 없이 딜을 넣는 편이 빠릅니다. 쓰러진 포켓몬은 다시 참여해 이어 싸울 수 있고, 되살리는 데 시간이 걸리므로 두 번째 파티도 미리 준비해 두세요." },
        { h: "자주 하는 실수", p: "① 보스 타입만 보고 약점 타입을 잘못 고르기(이중 타입은 두 타입을 모두 고려). ② 종족값만 보고 기술이 안 맞는 포켓몬을 넣기. ③ 날씨 부스트 없는 날에 사탕·XL이 필요한 보스를 잡기(부스트 날을 기다리면 파워업 비용 절약). ④ 인원이 부족한데 원격 초대를 안 쓰기. ⑤ 포획 시 커브볼·골드 나나를 안 쓰기(전설 포획률은 낮으므로 매 공 커브+엑설런트가 기본). 딜러 티어표에서 보스 약점별 최강 공격수를 확인하고, 레이드 일정 페이지에서 이달 보스와 날씨 부스트 타입을 미리 보세요." },
      ],
    },
    en: {
      title: "Pokémon GO Raid Basics — Tiers, Passes, Weather Boost, 100% CP and Mega Bonuses",
      desc: "Raids are where Pokémon GO's Legendaries, Mega Pokémon and strongest attackers come from. Raid tiers and group sizes, pass types, catch level 20 and weather-boosted 25, how to spot a 100% IV catch, Mega Evolution bonuses, attacker team building, dodging, and common mistakes.",
      sections: [
        { p: "A Raid Battle is a fight against a boss Pokémon at a Gym, taken on by several trainers together within a time limit; win and you get a chance to catch it. Legendaries, Mega Energy, Rare XL Candy and most top attackers come from raids, so whether you play PvP or PvE, raids are unavoidable." },
        { h: "Raid tiers and how many trainers you need", p: "Raids come as 1-star (soloable), 3-star (soloable at high level, otherwise 2–3 trainers), 5-star (Legendary, usually 4–8), Mega (3–6), Shadow Raids (in-person only, with an enraged phase that gets harder) and special tiers such as Elite and Primal. The number needed depends on trainer levels, attacker quality, weather and the boss's type; bringing six attackers from the raid attacker tier list is the surest way to need fewer people." },
        { h: "Types of Raid Pass", p: "A free Raid Pass comes from spinning a Gym once per day (with a holding limit); Premium Battle Passes are bought in the shop for in-person raids. Remote Raid Passes let you join distant raids but carry a daily limit and a price, and some raids such as Shadow Raids cannot be done remotely. The invite feature lets friends join remotely, so 5-star raids are possible even without a local community." },
        { h: "Catch level 20, weather boost 25", p: "Raid catches are fixed at level 20 with an IV floor of 10/10/10. If the current weather boosts the boss's type (for example sunny weather for a Fire type), the catch is level 25 with higher CP and bonus Candy, effectively saving power-up costs. The floor of 10 makes raids a poor source of low-Attack PvP spreads, but the best source of high-IV Master League Pokémon." },
        { h: "How to spot a 100% catch", p: "The CP shown on the catch screen tells you the IVs. A 15/15/15 catch shows a specific CP at level 20, which changes to the level-25 value under weather boost. GBL Note's 'Raid boss 100% CP' page lists this month's bosses with normal and boosted 100% CP plus CP-by-IV tables, so check it before the encounter and you will know the IVs at once. Beyond 15/15/15, anything with 15 Attack and 14–15 Defense and HP is more than enough for raids and Master League." },
        { h: "Mega Evolution bonuses", p: "When a Mega-Evolved Pokémon joins a raid, every participant's attacks that match the Mega's type are boosted, and catching Pokémon of that type afterwards awards extra Candy. Higher Mega Levels increase the bonus and add XL Candy chances. Bringing one Mega of a type the boss is weak to is the most efficient way to reduce the group size. Bonuses from identical Megas do not stack, so coordinate different Mega types among the group." },
        { h: "Attacker teams and dodging", p: "Fill your six slots with Pokémon whose fast and Charged Attacks both hit the boss's weakness; high base stats with the wrong moves lose a lot of DPS. Dodging (swiping) reduces damage from the boss's Charged Attacks but costs damage output, so with enough trainers it is faster not to dodge. Fainted Pokémon can rejoin after revival, which takes time, so prepare a second team in advance." },
        { h: "Common mistakes", p: "① Picking the wrong counter type by looking at only one of the boss's types. ② Choosing attackers by base stats while ignoring moves. ③ Catching a boss you need Candy or XL from on a non-boosted day (waiting for the boost saves power-up costs). ④ Not using remote invites when short on people. ⑤ Skipping Curveballs and Golden Razz on the catch; Legendary catch rates are low, so Curveball plus Excellent on every throw is the baseline. Check the attacker tier list for the boss's weaknesses and the raid schedule page for this month's bosses and their boosting weather." },
      ],
    },
    ja: {
      title: "ポケモンGO レイド入門 — ランク・パス・天候ブースト・100%個体CP・メガボーナス",
      desc: "レイドはポケモンGOで伝説・メガシンカポケモンと強力なアタッカーを得る核心コンテンツです。レイドランク別の難易度と必要人数、パスの種類、捕獲レベル20と天候ブースト25、100%個体のCP確認法、メガシンカボーナス、アタッカー編成と回避、よくあるミスをまとめました。",
      sections: [
        { p: "レイドバトルはジムに現れたボスポケモンを複数のトレーナーが一緒に攻撃して制限時間内に倒し、成功すればそのポケモンを捕獲する機会を得るコンテンツです。伝説のポケモン、メガエナジー、ふしぎなアメXL、強力なアタッカーの大半がレイドから出るため、PvP・PvEどちらをやるにしてもレイドは避けられません。" },
        { h: "レイドランクと必要人数", p: "レイドは★1（ソロ可）、★3（高レベルならソロ、通常2〜3人）、★5（伝説、通常4〜8人）、メガ（3〜6人）、シャドウレイド（現地参加のみで、後半の激怒状態で難しくなる）、そして特別ランク（エリート・ゲンシなど）に分かれます。必要人数は参加者のレベル、アタッカーの準備状況、天候、ボスのタイプで大きく変わるため、アタッカーティア表の推奨アタッカーを6匹揃えて行くのが人数を減らす最も確実な方法です。" },
        { h: "レイドパスの種類", p: "無料レイドパスはジムのフォトディスクを回して1日1枚もらえ（所持上限あり）、プレミアムバトルパスはショップで購入して現地レイドに使います。リモートレイドパスは遠くのレイドに参加できますが1日の使用制限と価格があり、シャドウレイドのようにリモート不可のレイドもあります。レイド招待機能でフレンドをリモート参加させられるため、地域コミュニティがなくても★5レイドを倒せます。" },
        { h: "捕獲レベル20、天候ブースト25", p: "レイドで捕まえるポケモンはレベル20固定で、個体値の下限は10/10/10です。そのボスのタイプに合う天候（例：ほのおタイプに晴れ）が適用されるとレベル25で捕まりCPが上がり、アメも追加されます。そのため同じボスでも天候ブースト状態の個体は強化コストを節約できることになります。一方PvP用の低攻撃個体はレイドでは得にくく（下限10）、マスターリーグ用の高個体値はレイドが最適です。" },
        { h: "100%個体のCP確認法", p: "捕獲画面のCPで個体値を推測できます。15/15/15の個体はレベル20で決まったCP（ボスごとに異なる）になり、天候ブースト時はレベル25のCPに変わります。GBL Noteの「レイドボス100%CP」ページは今月のボスの通常・天候ブースト100%CPと個体値別CP表を提供するため、捕獲前に確認しておけば捕まえた瞬間に個体値が分かります。通常15/15/15以外にも、攻撃15で防御・HPが14〜15の個体はレイド・マスターリーグ用途に十分です。" },
        { h: "メガシンカボーナス", p: "メガシンカポケモンがレイドに参加すると、そのメガと同じタイプのわざを使う全参加者の攻撃が強化され、レイド後の捕獲時に同じタイプのポケモンのアメが追加されます。メガレベルが上がるほどボーナスが大きくなり、XLアメの確率も付きます。したがってボスの弱点タイプのメガを1匹パーティに入れるのが人数を減らす最も効率的な方法です。ただし複数人が同じメガを入れてもボーナスは重複しないため、パーティ内で異なるタイプのメガを分担するのが良いです。" },
        { h: "アタッカー編成と回避", p: "パーティ6匹はボスの弱点を突くタイプで揃え、通常わざとゲージわざの両方がそのタイプでないとDPSが出ません。種族値が高くてもわざが合わなければ火力は大きく落ちます。回避（画面スワイプ）はボスのゲージわざのダメージを減らしますがその間火力を入れられないため、人数が十分なら回避せず攻撃するほうが速いです。倒れたポケモンは再参加して戦い続けられ、復活には時間がかかるため2つ目のパーティも事前に準備しておきましょう。" },
        { h: "よくあるミス", p: "①ボスのタイプの片方だけ見て弱点タイプを間違える（複合タイプは両方を考慮）。②種族値だけ見てわざが合わないポケモンを入れる。③アメ・XLが必要なボスを天候ブーストのない日に捕まえる（ブーストの日を待てば強化コストを節約）。④人数が足りないのにリモート招待を使わない。⑤捕獲時にカーブボール・きんのズリのみを使わない（伝説の捕獲率は低いので毎回カーブ＋エクセレントが基本）。アタッカーティア表でボスの弱点別最強アタッカーを確認し、レイドスケジュールページで今月のボスとブースト天候を事前に見ておきましょう。" },
      ],
    },
    "zh-TW": {
      title: "寶可夢 GO 團體戰入門 —— 等級・入場券・天氣加成・100% CP・超級進化加成",
      desc: "團體戰是寶可夢 GO 取得傳說・超級進化寶可夢與強力攻擊手的核心內容。整理團體戰等級難度與所需人數、入場券種類、捕捉等級 20 與天氣加成 25、100% CP 確認方法、超級進化加成、攻擊手隊伍組成與閃避，以及常見錯誤。",
      sections: [
        { p: "團體戰是多位訓練家一起攻擊出現在道館的頭目寶可夢，在限時內擊倒後獲得捕捉機會的內容。傳說寶可夢、超級能量、神奇糖果 XL 與大多數強力攻擊手都來自團體戰，因此無論玩 PvP 或 PvE，團體戰都無法避免。" },
        { h: "團體戰等級與所需人數", p: "團體戰分為 1 星（可單刷）、3 星（高等級可單刷，通常 2〜3 人）、5 星（傳說，通常 4〜8 人）、超級（3〜6 人）、暗影團體戰（僅限現場參加，後半的狂暴狀態更難）以及特殊等級（精英・原始等）。所需人數依參加者等級、攻擊手準備狀況、天氣與頭目屬性差異很大，帶齊攻擊手強度表推薦的 6 隻攻擊手是減少人數最可靠的方法。" },
        { h: "團體戰入場券種類", p: "免費團體戰入場券每天轉道館相片轉盤可獲得 1 張（有持有上限），高級對戰入場券在商店購買用於現場團體戰。遠距團體戰入場券可參加遠處的團體戰，但有每日使用限制與價格，且暗影團體戰等部分團體戰無法遠距參加。透過邀請功能可讓好友遠距參加，沒有在地社群也能打 5 星團體戰。" },
        { h: "捕捉等級 20、天氣加成 25", p: "團體戰捕捉的寶可夢固定為等級 20，個體值下限 10/10/10。若當時天氣符合頭目屬性（例：火屬性遇晴天），則以等級 25 捕捉、CP 更高並額外獲得糖果，等於節省強化費用。相對地，PvP 用的低攻擊個體很難從團體戰取得（下限 10），大師聯盟用的高 IV 則以團體戰最佳。" },
        { h: "100% CP 確認方法", p: "捕捉畫面的 CP 可推測個體值。15/15/15 的個體在等級 20 有固定 CP（各頭目不同），天氣加成時變為等級 25 的 CP。GBL Note 的「團體戰頭目 100% CP」頁面提供本月頭目的一般・天氣加成 100% CP 與各個體值 CP 表，捕捉前先確認就能在捕捉當下得知個體值。除 15/15/15 外，攻擊 15、防禦・HP 14〜15 的個體用於團體戰・大師聯盟也已足夠。" },
        { h: "超級進化加成", p: "超級進化寶可夢參加團體戰時，所有參加者使用與該超級進化相同屬性的招式攻擊都會強化，戰後捕捉同屬性寶可夢會額外獲得糖果。超級等級越高加成越大，並附帶 XL 糖果機率。因此在隊伍中放入一隻頭目弱點屬性的超級進化寶可夢，是減少人數最有效率的方法。但多人放入相同超級進化加成不會疊加，隊友之間最好分配不同屬性的超級進化。" },
        { h: "攻擊手隊伍組成與閃避", p: "6 隻隊伍以剋制頭目弱點的屬性組成，且一般招式與特殊招式都要是該屬性才有 DPS。種族值再高，招式不對傷害就大幅下降。閃避（滑動畫面）可減少頭目特殊招式的傷害，但期間無法輸出，人數足夠時不閃避直接輸出更快。倒下的寶可夢可重新加入繼續戰鬥，復活需要時間，請事先準備第二隊。" },
        { h: "常見錯誤", p: "① 只看頭目其中一個屬性而選錯剋制屬性（雙屬性要同時考慮）。② 只看種族值放入招式不對的寶可夢。③ 在沒有天氣加成的日子捕捉需要糖果・XL 的頭目（等加成日可節省強化費用）。④ 人數不足卻不用遠距邀請。⑤ 捕捉時不用曲球・金色蔓莓果（傳說捕捉率低，每球曲球＋Excellent 是基本）。請在攻擊手強度表確認各頭目弱點的最強攻擊手，並在團體戰日程頁面預先查看本月頭目與加成天氣。" },
      ],
    },
  },
};
